### ISSUE TITLE
No documentation on how to configure Azure App Configuration with non-minimal API

### ISSUE THREAD

**Issue by kikaragyozov** [Azure/AppConfiguration#1001]
Resource: https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app?tabs=entra-id

The documentation fails to mention how you'd be able to do a connection string configuration using a non-minimal API approach.

Is it even possible, without doing an anti-pattern involving the building of an `IConfigurationBuilder` twice, in the event you wish to store the connection string in the `IConfiguration`?

The new minimalistic builder comes with other internal changes to the whole experience, such as an integrated development error handler. We do not wish to migrate to it for those reasons and see no reason to not be able to do the same configuration with the old builder?

```
// Retrieve the endpoint
string endpoint = builder.Configuration.Get("Endpoints:AppConfiguration");
```

The above code copied from the linked material seems to fail compilation under net8/net9.

**Comment by albertofori** [comment]
Hello @kikaragyozov ,

Thanks for reaching out! We are looking into this and will revert shortly.

**Comment by amerjusupovic** [comment]
@kikaragyozov First, thank you for pointing out that issue in the link, we'll make sure to update the example for getting your endpoints with the proper .NET versions.

As far as retrieving the connection string from `IConfiguration`, I don't see a way to do so at the moment without calling build once before calling `AddAzureAppConfiguration` and building again, either explicitly or implicitly through a different builder interface. [Our examples that use the non-minimal API](https://github.com/Azure/AppConfiguration/blob/2ea44574dd51c6e0674e8ac0c5e907b28a3087eb/examples/DotNetCore/ConsoleApplication/Program.cs#L27) had the same approach, calling `Build()` twice on the same `IConfigurationBuilder`.

I'll keep looking into this, but I'm not sure what the solution is yet. The `AddAzureAppConfiguration` API needs access to the connection string, and there seems to be no way to access the configuration from within this API call since it's still being built.

**Comment by zhenlan** [comment]
@kikaragyozov thanks for reporting the issue. I have a PR out to fix the code issue you mentioned in the document.

You can find the following discussion at the end of the [step 3 in the said document](https://learn.microsoft.com/azure/azure-app-configuration/quickstart-aspnet-core-app?tabs=connection-string#connect-to-the-app-configuration-store):

> Secret Manager stores the secret outside of your project tree, which helps prevent the accidental sharing of secrets within source code. It's used only to test the web app locally. When the app is deployed to Azure like [App Service](https://learn.microsoft.com/en-us/azure/app-service/overview), use the Connection strings, Application settings or environment variables to store the connection string.

Regardless of whether you're using a minimal API, you can always save and read the connection string directly from the environment variable.

**Comment by zhenlan** [comment]
The document fix has been published.
