### ISSUE TITLE
Target date for G.A

### ISSUE THREAD

**Issue by msmaverick2018** [Azure/AppConfiguration#105]
What is the target date for general availability of Feature Management and also is it stable enough to be used in production grade apps? Has anyone used it already in a high traffic site?

**Comment by ArieJones** [comment]
Are you just talking about the Feature Management portion or AppConfiguration service in Azure. We are currently using Feature Management in a large production project right now .. no issues. I have another project that is spinning up at the moment that is using Feature Management + Azure AppConfiguration for a microservices environment... so I should be able to see any issues within the next month or so .

**Comment by msmaverick2018** [comment]
@ArieJones Thanks for the response. I am looking at the Feature Management portion. I looked at the issue raised https://github.com/Azure/AppConfiguration/issues/85 with regards to the feature check being a synchronous operation hence blocking in nature. In my case from my feature filter, in order to feature online/offline check, i have to call a microservice which checks a database table for a feature being on/off.

**Comment by ArieJones** [comment]
Yeah but it also caches .. so in my case I have a custom configuration db provider that I poll the database every X number of seconds to refresh the list of features and statuses. So it's not as if it is calling it every time you ask if feature X is on/off.

**Comment by zhenlan** [comment]
We don't have a specific date for the feature management library to release a stable version at the moment. We are aiming sometime in the fall.

What @ArieJones suggested sounds like a good solution to me regardless if async is supported by the feature management library. I'll have the async support discussion in #85, but I don't think it should be blocking the first stable release since it will be an addition if support is added.
