### ISSUE TITLE
Feature management dependency on Mvc could be split

### ISSUE THREAD

**Issue by naebliss** [Azure/AppConfiguration#111]
Hi,

We are working on a .net core application with a backend consisting of both WebApi and serverless function apps.

Currently there is a strong dependency on 'Microsoft.AspNetCore.Mvc.TagHelpers (2.2.0)'.
We would like to minimize our dependencies.

Are you planning on supporting multiple NuGet packages? 1 for the core feature filters functionality and 1 supporting mvc?

Kind Regards,
Robbie

**Comment by zhenlan** [comment]
@naebliss, you can use [Microsoft.FeatureManagement](https://www.nuget.org/packages/Microsoft.FeatureManagement) package, which is a .NET Standard library and has no dependency on ASP.NET Core, in your serverless function app. 

The [Microsoft.FeatureManagement.AspNetCore](https://www.nuget.org/packages/Microsoft.FeatureManagement.AspNetCore) is actually built on top of Microsoft.FeatureManagement with the addition of ASP.NET Core features.

**Comment by naebliss** [comment]
Thanks for the reply.

We managed to get it working using the following packages.
- Microsoft.FeatureManagement (1.0.0-preview-009000001-1251)
- Microsoft.Extensions.Configuration.AzureAppConfiguration (2.0.0-preview-009200001-1437)

however we noticed that if you want to have configuration refreshing you need to take a dependency on `Microsoft.Azure.AppConfiguration.AspNetCore` using the `AzureAppConfigurationRefreshMiddleware` which takes a dependency on `Microsoft.AspNetCore.Mvc.TagHelpers` for some reason. 
We rolled our own version of this `AzureAppConfigurationRefreshMiddleware`, perhaps you can take a look as to why this dependency exists?

**Comment by jimmyca15** [comment]
@naebliss 

That is by design. Microsoft.Azure.AppConfiguration.AspNetCore is a package which provides all the client-side functionality of Azure App Configuration for ASP.NET Core. This includes configuration provider, configuration refresh, feature management, and all the feature management integration points (including tag helpers). The value here is that one package can be used to start working with all that Azure App Configuration has to offer. From what you are saying it seems like that could be an issue because it brings in unnecessary MVC dependencies into a raw asp.net core app. 

It's a valid point, we can discuss this and see if making some other meta-package is a more reasonable approach to enable scenarios like yours. For example, "Microsoft.Azure.AppConfiguration.AspNetCore" (Only exposes the refresh middleware, and config provider) and "Microsoft.Azure.AppConfiguration.AspNetCore.All" (contains the previous package plus feature management).

**Comment by zhenlan** [comment]
We just released a new version of `Microsoft.Azure.AppConfiguration.AspNetCore` which removed the reference to `Microsoft.FeatureManagement.AspNetCore`. Please check out the [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md#200-preview-010060003-1250---october-03-2019).
