### ISSUE TITLE
Support for generics

### ISSUE THREAD

**Issue by vany0114** [Azure/AppConfiguration#114]
Guys, you might consider providing a way for both SDK and REST API's to update/set/add a configuration using generics? I'm using Azure App Configuration to get and also to write the configuration from my web app, so for writing, I'd like to do something like this:

```
await client.SetAsync<MySettings>(mySettings);
```
After that, I would expect to see the same result you get when you import a `json` file from azure portal:
![image](https://user-images.githubusercontent.com/12032625/61423843-ee8a0080-a8d6-11e9-926a-8a9c58c1e1a6.png)

That way I don't need to make a request for every key in `MySettings`, not to mention it would be easier.

**Comment by jimmyca15** [comment]
@vany0114, thanks for the suggestion. The intent when performing an operation like that can vary greatly between applications. For example, how the keys should be structured. Also our focus is on delivering configuration as individual settings rather than prescribing object models. For most purposes of App Configuration, keeping it simple and working on our plain key-value or "Setting" object is the best course of action.
