### ISSUE TITLE
App configuration refresh interval time in Azure Function

### ISSUE THREAD

**Issue by klogan12** [Azure/AppConfiguration#129]
I am accessing app configuration from my azure function , does azure function automatically refresh and get the updated values? If yes what is the time interval and is it configurable?

**Comment by zhenlan** [comment]
@klogan12 are you using `ConfigurationBuilder` like this [quickstart](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-function-csharp) in your Azure Function? If so, I believe it fetches the configuration every time your Azure Function is triggered.

**Comment by klogan12** [comment]
Yes i use configurationBuilder , but i do not create Builder object every time i access the config..
I have a seperate class that reads config and expose those values to my azure functions.

   _var builder = new ConfigurationBuilder();
    builder.AddAzureAppConfiguration(Environment.GetEnvironmentVariable("ConnectionString"));
    var config = builder.Build();
    string message = config["TestApp:Settings:Message"];_

So anytime my function wants to get Message it calls below code. Object is not recreated.
config["TestApp:Settings:Message"];

**Comment by zhenlan** [comment]
@klogan12 thanks for sharing the details. What are the times your *separate class* will be instantiated? Will it be upon every time your Azure Function is triggered? If not, how is the instance of your *separate class* shared between 2 Azure Function calls?

**Comment by klogan12** [comment]
It is a singleton class that gets instantiated once during the application lifetime,
Each function will refer this class to get all config values

**Comment by zhenlan** [comment]
@klogan12 in this case, since you always use the same instance of `IConfiguration`, the configuration from the App Configuration will *not* be reloaded automatically upon every call to your Azure Function.

If you like the configuration to be refreshed from the App Configuration once a while automatically, here is the code snippet you can do so

1. Create singleton `IConfiguration` and `IConfigurationRefresher` (they can also be members of your singleton class). For example,
```cs
private static IConfiguration _config;
private static IConfigurationRefresher _refresher;
```
2. In your singleton class when you add App Configuration provider to `ConfigurationBuilder`, register to refresh all configuration when a sentinel key is changed (you can also register to only refresh one particular key). The default cache expiration is 30 seconds. You can change it to something else you prefer. For example,
```cs
var builder = new ConfigurationBuilder();
builder.AddAzureAppConfiguration(o =>
{
    o.ConnectWithManagedIdentity("https://contoso.azconfig.io")
     .ConfigureRefresh(ro =>
        ro.Register("Sentinel", LabelFilter.Null, refreshAll: true)
          .SetCacheExpiration(TimeSpan.FromSeconds(60)));
    _refresher = o.GetRefresher();
});
_config = builder.Build();
```
3. In your Azure Function, call refresh before accessing the configuration (please make sure the singleton instances are created before calling them). For example,
```cs
await _refresher.Refresh();
string message = _config["TestApp:Settings:Message"];
```
Please note the `_refresher.Refresh()` will be just no-op if cache expiration window is not reached since last refresh so you don't need to worry it reloads all configuration upon every Azure Function call.

In the above example, your `message` will pick up the new value in 60 seconds after the "Sentinel" key is changed in App Configuration.

Please let me know if this works for you. You can also find more details at 
[Tutorial: Use dynamic configuration in a .NET Core app](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core).

**Comment by klogan12** [comment]
I am getting this error when builder.Build() is  being  called..


[8/29/2019 12:18:33 AM] System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Extensions.Configuration.AzureAppConfiguration: endpoint.


Here is my code in construction of static class.
var builder = new ConfigurationBuilder();
            builder.AddAzureAppConfiguration(o =>
            {
                o.ConnectWithManagedIdentity(Environment.GetEnvironmentVariable("ConnectionString"))
                 .ConfigureRefresh(ro =>
                    ro.Register("Sentinel", LabelFilter.Null, refreshAll: true)
                      .SetCacheExpiration(TimeSpan.FromSeconds(60)));
                Refresher = o.GetRefresher();
            });

            var config = builder.Build();

**Comment by zhenlan** [comment]
@klogan12 when you use `ConnectWithManagedIdentity(...)` to connect to App Configuration, please pass the endpoint to the API instead of the connection string and make sure you follow this [doc](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity) to grant permission accordingly.

**Comment by zhenlan** [comment]
@klogan12 please let me know if this works for you. BTW, if you prefer to use the connection string to connect to the App Configuration, which is fine too. In this case, you can use the API `o.Connect(Environment.GetEnvironmentVariable("ConnectionString"))` to replace the `o.ConnectWithManagedIdentity(...)` in my sample code above.

**Comment by klogan12** [comment]
@zhenlan  i am able to proceed.But when i change a key value in app config... Updated value is not refreshed..

**Comment by zhenlan** [comment]
@klogan12, glad to see the progress. After you make changes to key-values in the App Configuration, please also make a change to the "Sentinel" key (please create one if you don't have such). This will signal your Azure Function to refresh the configuration once the current configuration cache window expires (60 seconds in my sample code above).

**Comment by zhenlan** [comment]
@klogan12 just to check if you get a chance to give this a try?

**Comment by klogan12** [comment]
@zhenlan Sorry for the delay. It works thanks a lot !

**Comment by brphelps** [comment]
@zhenlan  -- Is there an issue open to have a better pattern around refreshing for azure functions? I'm using a global startup and it feels pretty hacky to pull a lambda argument out and then register it as a singleton so other pieces of the app can inject it.

**Comment by zhenlan** [comment]
@brphelps in an MVC app, we are working on making it easy to obtain the instance of the refresher from DI, but in a console or function app, there is not much option, for example, it does not sound right to return the instance through ConfigurationBuilder (via an extension method) either. Any suggestions?

**Comment by swasun99** [comment]
Any suggestions on how to obtain the instance of ConfigurationRefresher in the Azure function. I use a global startup where I do the initialization and therefore dont have the instance in my Azure Function. I expected it to work through DI but it doesnt. Any inputs?

**Comment by brphelps** [comment]
This is what I do-- I don't like it, because I have to build a configuration instance in order consume it correctly, so I think it could be particularly wasteful in some usage patterns (e.g. frequent cold starts). 
```
            var configuration = configurationBuilder.Build();
            IConfigurationRefresher configurationRefresher = null;
            //// Interim build because azure app configuration configuration doesn't support us doing it later, when we want to.
            configurationBuilder.AddAzureAppConfiguration((AzureAppConfigurationOptions appConfigOptions) =>
            {
                appConfigOptions
                    .Connect(configuration.GetSection("AppConfiguration").GetChildren().FirstOrDefault(x => x.Key == "ReadOnlyConnectionString").Value)
                    .UseFeatureFlags(x => x.CacheExpirationTime = TimeSpan.FromSeconds(10))
                    .ConfigureRefresh(x =>
                    {
                        x.Register("Sentinel", LabelFilter.Null, refreshAll: true);
                        x.SetCacheExpiration(TimeSpan.FromSeconds(10));
                    });
                configurationRefresher = appConfigOptions.GetRefresher();
            });
            configuration = configurationBuilder.Build();
            var services = builder.Services;

            services.AddFeatureManagement(configuration);
            services.AddSingleton(configurationRefresher);
```

**Comment by zhenlan** [comment]
@swasun99 I have an on-going PR #266 for Azure Function. Please check it out.

**Comment by swasun99** [comment]
Thank you @brphelps and @zhenlan, am looking for a way to distinguish between a key-value setting and a keyvault reference setting in the AppConfiguration, do you have any pointers regarding it?

**Comment by calloncampbell** [comment]
Thank you @zhenlan for the example!
