### ISSUE TITLE
Offline Cache

### ISSUE THREAD

**Issue by jmsalvo** [Azure/AppConfiguration#137]
I saw a prior ticket related to the Offline Cache functionality, but I am still unclear how to use this feature.  I added the following to my code

 options.Connect(settings["ConnectionStrings:AppConfig"])
                            .SetOfflineCache(new OfflineFileCache(new OfflineFileCacheOptions
                            {
                                Path = "<Local Path>"
                            }))

It's unclear to me what SetOfflineCache is doing or if anything else needs to be done to cache configuration data locally and use the local cache when offline?  Is there a more complete example or explanation of this functionality?

**Comment by zhenlan** [comment]
@jmsalvo I apologize we are lack of documentation on this. You may have reviewed #45 already where I discussed what the API will be doing. Please note the `OfflineFileCache` will only work in *Azure App Service* currently. Since the whole idea of it is to work transparently, it will kick in automatically when your App Service application fails to connect to App Configuration at startup. You can find the encrypted cache file in App Service at *$home/data/azureAppConfigCache* in case you want to check whether the cache is created.

**Comment by jmsalvo** [comment]
Thank you for clarifying this only presently works for Azure App Services.

**Comment by avanigupta** [comment]
Hi @fernandozago, we are evaluating how Offline Cache is used in different applications. Could you please help us understand the problem you are trying to solve by using Offline Cache?
