### ISSUE TITLE
Can no longer access AppConfiguration in Azure or through code via keys

### ISSUE THREAD

**Issue by MrTortoise** [Azure/AppConfiguration#145]
We have been using AppConfiguratino for around 2 months.

For some reason today it has stopped working for me - today.

I have tried creating new resources but I get the same error - also have cycled the keys.

When I goto view feature flags I get 
`
Failed to load app configuration information from the server.
12:05 PM
An authorization error occurred while attempting to access the data.
`

I am a co-administrator - I created the resources. This was working then with no changes to anything on our end it stopped.

I appreciate this is a soft issue but cannot find another channel.
I also get this is in preview and something probably got rolled out 

Any ideas
thanks

**Comment by zhenlan** [comment]
Hi @MrTortoise thanks for reporting the issue. Do you mind to drop me an email as I'd like to learn some more details (store name, when did it occur, has it recovered etc.)?

**Comment by MrTortoise** [comment]
All seems to of started working again now.

We can continue the email exchange if you want. 
But I cannot reproduce anymore.

**Comment by zhenlan** [comment]
Thanks for the update, @MrTortoise. When this happens again, it's helpful to try in a new incognito window to avoid weird results due to browser caching. If you don't mind, can you please still drop me an email with the details I mentioned? I'd like to confirm there is nothing unexpected happening on the service side.
