### ISSUE TITLE
Storing Application Insights' Instrumentation Key in AzureAppConfig

### ISSUE THREAD

**Issue by nickalbrecht** [Azure/AppConfiguration#162]
Environment details:
ASP.NET Core application (discovered in 2.2, reproduced in 3.0 before filing issue), Not sure if this is a caveat/bug for ApplicationInsights or AzureAppConfiguration, but I wanted to bring it up.

I believe I may have found a compatibility issue when using the default setup with Application Insights and Azure App Configuration? It seems like something in the AzureAppConfiguration is triggering the `TeletryClient` (and consequently the `TelemetryConfiguration`) to be instantiated when there's no key defined yet (since it's stored in the Azure App Config), and because they are only created once it never uses the key it will obtain from AzureAppConfiguration.

Reproduce:
Have an AzureAppConfig setup with at least one key/value pair of `ApplicationInsights:InstrumentationKey` and a valid instrumentation key for its value, (empty label)

New ASP.NET Core application
*I went for 3.0 with MVC pattern, but I don't it matters in this instance
Add reference to Microsoft.ApplicationInsights.AspNetCore
Add reference to Microsoft.Extensions.Configuration.AzureAppConfiguration
My CreateHostBuilder inside of Program.cs is as follows

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((context, config) => {
            var appConfigName = "..."; //Name of the AzureAppConfig

            config.AddAzureAppConfiguration(options => {
                options.ConnectWithManagedIdentity($"https://{appConfigName}.azconfig.io")
                    .Use("*", labelFilter: LabelFilter.Null);
            });
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

Within one of the `cshtml` files (I just put this in _Layout)
```
@using Microsoft.ApplicationInsights.Extensibility
@using Microsoft.Extensions.Configuration
@inject TelemetryConfiguration telemetryConfiguration
@inject IConfiguration config
```

```
<div id="config">@config["ApplicationInsights:InstrumentationKey"]</div>
<div id="telemetry">@telemetryConfiguration.InstrumentationKey</div>
```

The InstrumentationKey pulled from the config will have the value from the AzureAppConfig, but the telemtry client will not.

If you put the instrumentation key in any of the local appconfig.json files (appconfig.json, appconfig.development.json, or even the secrets.json file) then both statements will have the correct instrumentation key.

**Comment by sabbadino** [comment]
Same for me : this  does not work 
            services.AddApplicationInsightsTelemetry();
While this works : 
            var key = Configuration["ApplicationInsights:InstrumentationKey"];
            services.AddApplicationInsightsTelemetry(key);

**Comment by abhilasharora** [comment]
The current implementation of `IServiceCollection.AddApplicationInsightsTelemetry` extension method with no arguments uses the [default options](https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/develop/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs) that only use configuration from certain locations specified in the following code.

```
var configBuilder = new ConfigurationBuilder()
    .SetBasePath(this.hostingEnvironment.ContentRootPath ?? Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", true)
    .AddJsonFile(string.Format(CultureInfo.InvariantCulture, "appsettings.{0}.json", this.hostingEnvironment.EnvironmentName), true)
    .AddEnvironmentVariables();

ApplicationInsightsExtensions.AddTelemetryConfiguration(configBuilder.Build(), options);
```

It is possible to update the implementation of the following method in Application Insights to retrieve configuration from `IConfiguration` injected within the service collection.

````
public static IServiceCollection AddApplicationInsightsTelemetry(this IServiceCollection services);
````

However, this approach is not guaranteed to work, since `IConfiguration` registered in the service collection may not be instantiated at the time of initialization of `TelemetryClient`. An explicit instantiation of `IConfiguration` in the Application Insights code would cause an additional unintended load of data from all configuration providers. Therefore, this is not a good idea.

In order to enable the settings within App Configuration to be used, I would suggest using the following overload of `AddApplicationInsightsTelemetry` that takes an `IConfiguration` instance as an additional parameter. This will ensure that the settings within this instance would be used for initialization of `TelemetryClient`.

````
public static IServiceCollection AddApplicationInsightsTelemetry(this IServiceCollection services, IConfiguration configuration);
````



#### Working Code for `Startup.cs`

````
public IConfiguration Configuration { get; }

public Startup(IConfiguration configuration)
{
    Configuration = configuration;
}

public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();
    services.AddApplicationInsightsTelemetry(Configuration);
}
````

We will add this usage sample to our documentation to make it easier for other users to avoid this issue.
