### ISSUE TITLE
Internal server error when creating App Configuration using Azure SDK for Go

### ISSUE THREAD

**Issue by brennerm** [Azure/AppConfiguration#184]
I'm currently implementing a new Terraform resource to be able to create App Configuration instances. Using the Azure SDK for Go, creating works fine but requesting the operationsStatus I end up with following error response:
```json
{"id":"/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.AppConfiguration/locations/westeurope/operationsStatus/1acc3289-3f22-ce0d-e6a2-185a8e1d8576","name":"1acc3289-3f22-ce0d-e6a2-185a8e1d8576","status":"Failed","error":{"code":"InternalServerError","message":"Cannot serve the request. Please retry."}}
```
Below you can find the response from the creation request:
```
{"type":"Microsoft.AppConfiguration/configurationStores","properties":{"provisioningState":"Creating","creationDate":"2019-11-06T23:22:58.6
592674+00:00","endpoint":"https://foobarz.azconfig.io"},"sku":null,"id":"/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/test/providers/Microsoft.AppConfiguration/
configurationStores/foobarz","name":"foobarz","location":"westeurope","tags":{}}
```

For more information you can read through [my code](https://github.com/brennerm/terraform-provider-azurerm/blob/a367d2bdeb4e6a41a0d455539a20536e5203d070/azurerm/resource_arm_app_configuration.go#L69).

**Comment by jimmyca15** [comment]
Hello @brennerm,

It looks like this issue is caused by [specifying a non-valid SKU](https://github.com/brennerm/terraform-provider-azurerm/blob/a367d2bdeb4e6a41a0d455539a20536e5203d070/azurerm/resource_arm_app_configuration.go#L96) in the `sku` parameter of the configuration store resource. You can help confirm this by providing a valid SKU ("free" or "standard") and seeing if that fixes the issue.

Two questions may come up from this:
1. Where do you get the list of SKUs that are supported.

We are still in preview and expect most customers will use "free" as their SKU. We are currently adding a standardized Azure API which will allow all the SKUs available for each region to be listed. As we move forward we will ensure to document the available SKUs, which are a required parameter, as appropriate. There are descriptions for the two SDKs available [here](https://github.com/Azure/AppConfiguration-Announcements/issues/2): 

2. Why did the error message say "InternalServerError".

Looks like you helped us find a bug! The wrong error message is being returned. Thanks!

It looks like you jumped onto using the new Go SDK pretty quickly. Thanks for that.

**Comment by brennerm** [comment]
Hey @jimmyca15, thanks for coming back to me.

I had indeed trouble finding the correct SKU names so thanks for the explanation. Using `free` as the SKU resolved my problem and the deployment went through. :tada: Documenting these somewhere appropriate would definitely help other people to work with your API/SDK.

Always happy to help out, thanks for your support. :+1:
