### ISSUE TITLE
AppConfigurationBuilder Doc

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#234]
In the [AppConfigurationBuilder](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/master/README.md#azureappconfigurationbuilder) documentation, and the rest of the configuration builder syntax blocks, the parameters are often grouped together and not broken out individually.  

For example
````
<add name="AzureAppConfig"
    [mode|@prefix|@stripPrefix|tokenPattern|@escapeExpandedValues|@optional=false]
    (@endpoint="https://your-appconfig-store.azconfig.io" | @connectionString="Endpoint=https://your-appconfig-store.azconfig.io;Id=XXXXXXXXXX;Secret=XXXXXXXXXX")
    [@keyFilter="string"]
    [@labelFilter="label"]
    [@acceptDateTime="DateTimeOffset"]
	[@useAzureKeyVault="bool"]
````
It looks like `mode` contains one of several optional values instead of these values being valid in, and of, themselves.

I might have expected something like:
````
<add name="AzureAppConfig"
    [mode=strict|greedy]
    [@prefix="string"]
    [@stripPrefix=true|false]
    [tokenPattern="string"]
    [@escapeExpandedValues=true|false|
    [@optional=true|false]
    (@endpoint="https://your-appconfig-store.azconfig.io" | @connectionString="Endpoint=https://your-appconfig-store.azconfig.io;Id=XXXXXXXXXX;Secret=XXXXXXXXXX")]
    [@keyFilter="string"]
    [@labelFilter="label"]
    [@acceptDateTime="DateTimeOffset"]
	[@useAzureKeyVault="bool"]
````
Also there's the injection of the `(`. Does that mean `required`?

In the same thought, perhaps in the explanation had a required tag

* ` endpoint` - This specifies the AppConfigurationStore to connect to. (required. One of endpoint or connection string)

**Comment by zhenlan** [comment]
@HashTagDotNet good suggestions. Thanks!

@StephenMolloy thoughts?

**Comment by StephenMolloy** [comment]
That first group of options is grouped together because they apply to all config builders in the repo. Rather than taking more screen real estate in an already crowded doc page, I thought it would be easier to group them, since their meaning and use was already outlined in detail in the [section above](https://github.com/aspnet/MicrosoftConfigurationBuilders#keyvalue-config-builders). Breaking them all out individually on every builder felt overly verbose and redundant.

The '@' symbol means the setting can take advantage of [AppSettings Parameters](https://github.com/aspnet/MicrosoftConfigurationBuilders#appsettings-parameters), although the note that says that isn't really obvious when looking at an individual parameter in these syntax blocks. A quick search for '@' should turn up the designation, but I'm definitely open to a better way to do it on this one.

The use of `[ ]`'s denotes optional parameters. If square brackets aren't applied, then the option is required. Parentheses `( )`'s are used for grouping mutually exclusive parameters with an `|` (or). These are usually required parameters, so you don't also see `[ ]`'s around them. I didn't explicitly state these conventions anywhere, but hopefully the `required` and `mutually exclusive` designations are clear in the description for each parameter below the syntax box.

Again, I'm open to suggestions for a better way that makes the readme more understandable at a glance without contributing clutter. I think we should close this issue here, since the readme.md at hand is in the aspnet/MicrosoftConfigurationBuilders repo. If you have any suggestions for improving the syntax or how it gets (or doesn't get) explained, feel free to open an issue over there and assign it to me.
