### ISSUE TITLE
Possible encoding issue with CLI and values containing special characters

### ISSUE THREAD

**Issue by catbusstop** [Azure/AppConfiguration#283]
**Issue:**
When retrieving a key-value with certain special characters using the CLI, the returned value looks ok until the value is held as a variable or ConvertFrom-Json is used, at which point, certain characters change. £ becomes ú and € becomes Ç, possibly indicating an encoding issue.

**Steps to reproduce**
- Add a new key-value into AAC with a £ or € in either the name or the value (doesn't matter which, the issue occurs either way)
- Use the CLI to return the key-value: `az appconfig kv list --name 'appconfigname' --key 'Test:Settings:*'` - powershell output looks correct
- Use the CLI again, but this time, save the output to a variable: `$x = az appconfig kv list --name 'appconfigname' --key 'Test:Settings:*'`
- Now output $x and you get different values
- The same happens if you use ConvertFrom-Json: `az appconfig kv list --name 'appconfigname' --key 'Test:Settings:*' | ConvertFrom-Json`

**Comment by shenmuxiaosen** [comment]
After some offline discussion with CLI team, this issue is related to system's code page. As CLI is written by Python, when directly output to console, the output is UTF-8. But if the stdout is redirected, Python thinks the stdout is charmap thus can't encode the character. Here is a pull request related with this issue with solutions. https://github.com/microsoft/knack/pull/178#pullrequestreview-368163183

**Comment by zhenlan** [comment]
Closing as microsoft/knack#178 has merged.
