### ISSUE TITLE
Best Practice for handling local settings while development

### ISSUE THREAD

**Issue by LaurinSt** [Azure/AppConfiguration#315]
Hi there

I was searching through your documentation, which has many very useful inputs, thank you for this.
I am missing one point:
What is the best practice you propose for local development machine settings? It's clear to me that in Azure App Configuration Service you can have labels for different environments. But if you have 5 developers on a project you probably want all of them to add there local dev machine settings with labels. So is there any best practice for this? Or is it just help yourself and add a fallback to local appsettings with a preprocessor constant like #if debug?
Thanks for you help

**Comment by drago-draganov** [comment]
Hello @LaurinSt 

Suggestions may vary depending on your local dev environment. Is this .NET Core application or something else?

**Comment by LaurinSt** [comment]
Most of the times they are .net core asp.net web api projects. But how would it differ between console project and asp.net project?

**Comment by drago-draganov** [comment]
These all fall into the same category of .NET apps. I asked because we could've been talking about Java or something else.
I will assume here that you are using AzureAppConfiguration Provider as well. 

If you need to have different centralized dev profiles and share between the team, then using labels is a good start. 

If you want to allow devs to play locally with some settings (for debugging purpose or whatnot), then you can layer AzureAppConfiguration and local json file (ex. appsettings.dev.json) on top. .NET Core Configuration allows for multiple config providers. 
So use AzureAppConfiguration for all centralized settings and local appsettings.dev.json for devs to change stuff locally. Since appsetting.dev.json is after AddAzureAppConfiguration, it should override an existing centralized setting, as well as provide new as appropriate.

Perhaps something like this:

```cs
            var config = new ConfigurationBuilder()
                .AddAzureAppConfiguration(...)
                .AddJsonFile("appsettings.dev.json");
                .Build();
```

**Comment by LaurinSt** [comment]
Thanks. That's a nice way I was not aware of.

**Comment by iqoOopi** [comment]
@drago-draganov 
Hi drago,

We kind of want the same thing for our .net framework app. When debugging/running locally we don't want to call app configuration at all to save some cost. 
For your code:
`
var config = new ConfigurationBuilder()
                .AddAzureAppConfiguration(...)
                .AddJsonFile("appsettings.dev.json");
                .Build();`

I believe it will still make a call to the Azure app configuration then the local file will override them. Wondering how can we don't call it when local debugging.

Thanks

**Comment by drago-draganov** [comment]
@iqoOopi,

```cs
var configBuilder = new ConfigurationBuilder();

//
// Skip Azure AppConfiguration for dev environment
if (!env.IsDevelopment())
{
    configBuilder.AddAzureAppConfiguration(...);
}

var config = configBuilder
    .AddJsonFile("appsettings.dev.json");
    .Build();
```

**Comment by iqoOopi** [comment]
@drago-draganov Oh yes, thanks a lot.
