### ISSUE TITLE
Exporting Feature Manager keys has changed behaviour - breaking change!

### ISSUE THREAD

**Issue by upmygit** [Azure/AppConfiguration#318]
Previously I could press export to copy all keys from one App Configuration (Feature management) to the next one (acceptance -> production). It would merge all the keys on the target, and the state of already existing keys was left untouched. Great, just what I want!

**Previous behaviour**
| Acceptance | Production before export | Production after export |
|-|-|-|
| Toggle1 - On | Toggle1 - Off | Toggle1 - Off |
| Toggle2 - On | Toggle2 - Off | Toggle2 - Off |
| Toggle3 - Off |       n/a           | Toggle3 - Off |

**Notification shows 1 key exported! -- GOOD!**
<br>
**Current behaviour**
| Acceptance | Production before export | Production after export ||
|-|-|-|-:|
| Toggle1 - On | Toggle1 - Off | Toggle1 - **On** | CHANGED BEHAVIOUR! |
| Toggle2 - On | Toggle2 - Off | Toggle2 - **On** | CHANGED BEHAVIOUR! |
| Toggle3 - Off |       n/a           | Toggle3 - Off ||

**Notification shows 3 keys exported! -- BAD!**
<br>
Only now I saw this behaviour has changed, which is breaking for me. Why? Because the keys are used for feature toggling certain new routes and functionality. The state of existing keys in production should not be disturbed, because it causes big problems!

Why has this changed, and why no mention about this change??

**Comment by lisaguthrie** [comment]
@upmygit - what is the name of your store? (You can email me at lisa.guthrie@microsoft.com if you don't want to post it publicly.)

**Comment by upmygit** [comment]
@lisaguthrie - what do you mean by 'store'? The App Configuration resource?

**Comment by lisaguthrie** [comment]
@upmygit yes, exactly -- as it appears in the App Configuration resource list. For example, this store's name is AppConfigContoso:

![image](https://user-images.githubusercontent.com/26001667/80288273-d8259680-86eb-11ea-812a-f28c0553f5f4.png)

**Comment by upmygit** [comment]
@lisaguthrie - I just sent it via email

**Comment by upmygit** [comment]
@lisaguthrie - I haven't heard from you for awhile now, are you guys still investigating?

**Comment by lisaguthrie** [comment]
Hello @upmygit and apologies for the delay. Thank you for providing additional information via email. Unfortunately, our telemetry logs from your March session (where you saw values preserved on export) have already rolled over, so we were unable to investigate the behavior you saw. 

The behavior you're seeing right now has always been the expected behavior. We did confirm that we had no recent deployments touching that area of code, so we're unsure why you've seen a change in behavior.

We do understand your scenario here. We are investigating the possibility of adding an option allowing you to choose between overwriting vs. preserving values on export.

**Comment by upmygit** [comment]
@lisaguthrie - Let me guess, roll over happens after 90 days?
Will I be kept in the loop if such an option is added to the product backlog?

**Comment by lisaguthrie** [comment]
@upmygit - I've added it to our backlog, and I've also made a note to update this issue + you directly via email on any progress.

**Comment by zhenlan** [comment]
Closing this issue as the ask has been tracked internally.
