### ISSUE TITLE
App Configuration - cannot create key in an AppConfig that I created for myself

### ISSUE THREAD

**Issue by pthibodeaux** [Azure/AppConfiguration#340]
Get message: User is not authenticated to access configuration data
I created the App Configuration for myself and granted myself full access, but keep getting the message about when I try to create a simple key.
What am I missing?

**Comment by pthibodeaux** [comment]
{ "shellProps": { "sessionId": "a0a0c768ed26411690262117fe019331", "extName": "Microsoft_Azure_AzConfig", "contentName": "CreateEditItemBlade", "resourceId": "/subscriptions/ab481ec9-6660-4a83-aa3b-11a9d12b8520/resourceGroups/paulthib-rg1/providers/Microsoft.AppConfiguration/configurationStores/paulthib-appconfig1", "code": 403 }, "error": { "message": "User is not authenticated to access configuration data", "code": 401, "details": "Paul Thibodeaux (paul.thibodeaux@towerswatson.com) does not have the valid access keys to access configuration data. If the access key was recently regenerated, please reload this page to refresh your access keys.", "summaryItems": [ { "label": "Time stamp", "value": "6/5/2020, 9:13:11 AM" } ], "metadata": { "utc": "2020-06-05T15:13:11.455Z", "type": "KV" } }}

**Comment by pthibodeaux** [comment]
I tried granting both Owner and Contributor, but neither worked.   Shouldn't I have access to my own resources by default?   Thats how it works for keyvault.
This is just adding a key-value pair using the portal.

**Comment by zhenlan** [comment]
@pthibodeaux thanks for sharing details. This is not expected. We are looking into it.

**Comment by zhenlan** [comment]
@pthibodeaux we took a look at the logs of your store. It appears all the "read" requests have succeeded and all the "write" requests have failed. The "write" requests failed because the "authorization" header is missing and thus requests failed with 401 (not authenticated).

I have a hard time imagining why this could happen so I'd like to share the details above that might ring a bell for you. In addition, if you can try below, it may also help to isolate the issue.
- Try a different browser
- Try a different machine
- Try a different network, eg. use LTE on your phone
- Try to create a key-value using Azure CLI

Please let me know what you find out.

**Comment by pthibodeaux** [comment]
I killed my company VPN connection and tried it again,  Now it works.   
Then, I started VPN again and it seems to be working fine now.  
I guess it was something in the previous VPN session that was causing a problem.
Thanks

**Comment by zhenlan** [comment]
@pthibodeaux thanks for the update. I'm glad it worked for you.
