### ISSUE TITLE
App config - Keys got replicated automatically based on label

### ISSUE THREAD

**Issue by klogan12** [Azure/AppConfiguration#341]
Keys that were added without any label attached , is now displayed  n times in azure portal.
n - no of label we have. Is this a new change or a UI bug?

**Comment by zhenlan** [comment]
@klogan12 do you mind to share a screenshot?

cc: @jiayi11

**Comment by klogan12** [comment]
![image](https://user-images.githubusercontent.com/9304593/83929893-02468b80-a763-11ea-9bd0-3d368bf81154.png)

**Comment by jiayi11** [comment]
Hi @klogan12, could you please elaborate more on the problem you have so I can understand better? From this screenshot, seems you have four key-value pairs. All of them have the same Key name "Sentinel", but each has different labels. In our Config Explorer these are grouped together because they have the same key.

**Comment by zhenlan** [comment]
@klogan12 please let us know if you have further information.
