### ISSUE TITLE
v3 RBAC + Managed Application + MSI not working

### ISSUE THREAD

**Issue by wahyuen** [Azure/AppConfiguration#351]
Hoping to get some guidance or clarity if this was an intended design decision or perhaps an oversight.

We are currently still on the v2 preview version of the SDK and works well with our Managed Service Identities (MSI) of App Service/Function Apps communicating with App Configuration.

While attempting to upgrade to the v3 of the SDK and thus utilizing the new RBAC roles, we discovered that due to the fact our application is rolled out as a [Managed Application](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/overview) with `Deny Assignments`, this subsequently results in our MSI not being able to communicate with App Configuration, even with the correct RBAC roles.

It appears that a `Deny Assignment` takes precedence over `Allow` assignments. We are then left with a 'chicken/egg' scenario, where for this to work we should add the MSI as excluded principals to the `Deny Assignment`, but can't do this as we need the Managed Application defined first so that we can deploy our resources!

We don't seem to have this issue with using MSI for access to Key Vault...so I'm unsure if this is a unique scenario to App Configuration or whether this is by design or a consequence of moving to the new RBAC workflow.

**Comment by zhenlan** [comment]
@wahyuen not sure if the issue has been resolved. Lots of details are missing here, so it's hard to give any useful suggestions. Everything I said below is very generic. I am just trying to share some ideas.

You mentioned about managed applications. Are you the publisher or the consumer? Is App Configuration deployed in the managed resource group or application resource group? Where is it to be accessed from? 

The v2 preview App Configuration provider uses the "Contributor" or "Owner" roles to access data and the v3 is changed to use either the "App Configuration Data Reader" role or "App Configuration Data Owner" role to access data. Looks like you have difficulties to grant one of "Data" roles to your managed identity. Since v2 worked for you, maybe you can see how "Contributor" or "Owner" roles were assigned and follow the same?

Key Vault does not use the standard RBAC for its data access. It has its own "Access Policy", so the scenario could be different. If you also use the managed identity to access a storage account, that's where I would look and see if I can set up something similar for App Configuration.

**Comment by wahyuen** [comment]
@zhenlan Thanks for the reply, some answers to your questions...we haven't currently found a solution around this issue yet.

 - We are currently the 'publisher' of the application (ie. we deploy the code and manage the application for our customer) and the App Configuration instance is deployed in the managed resource group. We work with the customers IT department and have them provision our managed application inside their own tenant. Once everything is setup, the customer's users can access our application via their own Azure AD authentication.

- In v2, we simply used the code block of `options.ConnectWithManagedIdentity(appConfigurationEndpoint);` and use the MSI of the App Service (or Function app) to talk to App Configuration. We assign the MSI `Contributor` access to App Configuration itself as you mention and this seems to work. For v3, we performed the same steps but changed the permission to be `App Configuration Data Reader`, however, this does NOT seem to work for us as it appears the `Deny assignment` takes precedence over the role assignment. We had (perhaps naively) assumed this should work in the same manner as the v2 implementation?

**Comment by zhenlan** [comment]
Closing out old issues. Please reactivate if further assistance is needed.

**Comment by wahyuen** [comment]
For anyone else unlucky enough to come across this situation in the future...

After much back and forth between multiple MS teams it was established that this use case was an oversight in design and not catered for at all.

We ended up implementing a workaround, whereby we add an Azure AD Security Group as an exclusion 'principal' when creating the Managed Application. Then, once the managed resources are created, we can post process and assign the Managed Service Identity into this Azure AD Security Group, from which we can then grant access to App Configuration directly.

As there is no (at the time of writing) roadmap feature from the teams, this was the suggested way forward from support.
