### ISSUE TITLE
App Config Changes not reflecting and refreshed in application until property is used in spring boot App

### ISSUE THREAD

**Issue by oceansv** [Azure/AppConfiguration#384]
Issue : When a property is changed in app config , changes are not reflected in application , Once a property is fetched manually (even after 2 - 3mins ) it will give older value and soon after it new properties and retrieved .

App Setup ;
Java 1.8
Spring boot app
eclipse 

Description : 
dependency

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-cloud-azure-appconfiguration-config-web
			</artifactId>
			<version>1.2.7</version>
			<exclusions>
				<exclusion>
					<groupId>com.azure</groupId>
					<artifactId>azure-core</artifactId>  // This is excluded because newer version was needed .
				</exclusion>
			</exclusions>
		</dependency>

@ConfigurationProperties
public class Properties {
	
	@Value("${azure.cosmosdb.database}")
	private String azureCosmosdbDatabase;

	//getters, setters and tostring
        

}

@RestController
@RequestMapping("/")
public class HealthCheck {

	@Autowired
	private Environment env;
	
	@Autowired
	private Properties properties;
	
	Logger logger = LoggerFactory.getLogger(HealthCheck.class);
	@GetMapping(path = "/heartbeat")
	@ResponseBody
	@ResponseStatus(value = HttpStatus.OK)
	public String heartbeat() {
		System.out.println(env.getProperty("azure.cosmosdb.database"));
		System.out.println(properties.getAzureCosmosdbDatabase());
		
                return "up and running";
	}
}

Issue Elaboration:

1)  azure.cosmosdb.database = "value1" initially
1) azure.cosmosdb.database is changed  to "value2" in app config
2) By deafult 30 s of cache refresh is expected 
3) heartbeat is invoked after 2 min of change in property
4) 	System.out.println(env.getProperty("azure.cosmosdb.database")); this print value1 (expectation value2)
		System.out.println(properties.getAzureCosmosdbDatabase()); this print value1  (expectation value2)
5) Soon after it logs show property refresh starts
6) heartbeat is invoked again 
7) 	System.out.println(env.getProperty("azure.cosmosdb.database")); this print value2
		System.out.println(properties.getAzureCosmosdbDatabase()); this print value1  (expectation value2)

As per my understanding 2 expectation
1) In first call to heartbeat after 2 min of property change value2 should be printed
2) @ConfigurationProperties annotated class are expected to refresh and  reflect new properties

**Comment by mrm9084** [comment]
@oceansv So I have taken a look and this is because the property is being set at `azure.cosmosdb.database`. And your configuration in Properties is just using the placeholder value which is not being reset to the new value.

If you actually wanted to set that configuration you should give `@ConfigurationProperties` a prefix. i.e. 
```java
@ConfigurationProperties(prefix = "config")
```

Then set the configuration as `/application/config.azureCosmosdbDatabase`.

I will look into if there is a way to get it to work with what you tired to do.

**Comment by oceansv** [comment]
@mrm9084  What about Environment , properties inside  is that expected to be changed automatically? Because earlier i didnt even created 
@ConfigurationProperties 
Properties  class and was completely relying on properties present inside spring environment.

**Comment by mrm9084** [comment]
@oceansv Are you using spring-data-cosmosdb, or azure-cosmosdb-spring-boot-starter as dependencies, as they have `azure.cosmosdb.database` as a property.

If I read your explication correctly this is returning the correct value

```java
System.out.println(env.getProperty("azure.cosmosdb.database"));
```

This is because App Configuration is setting the value in spring-data-cosmosdb.

Sorry missed the first question. The App Configuration module only refreshes when activity occurs. We define as endpoint activity. So if the cache expires and no one touches the application for a hour no refresh will happen. The next activity will cause the refresh. This does result in the request that causes the refresh to not have the changes.

For more info see here: https://github.com/microsoft/spring-cloud-azure/tree/1.2.7/spring-cloud-azure-starters/spring-cloud-starter-azure-appconfiguration-config#configuration-refresh

**Comment by oceansv** [comment]
@mrm9084 As i saw in the library "public class ConfigListener implements ApplicationListener<ServletRequestHandledEvent>" a http request i that activity which result in fetching new properties. and any activity inside app like jms listener is not expected to change the properties.

**Comment by mrm9084** [comment]
@oceansv Only http requests through the Spring Controllers will cause refresh. i.e. only Spring Web applications will cause refreshes.  We have two libraries one that doesn't have a dependency on Spring Web. Both libraries allow for the applications to trigger a manual refresh check based on when ever you call it, see link above for info.

Your understanding of the order of operations is correct.

Not exactly sure what you mean by "Why independent polling is not there why to rely on incoming http calls?".

We rely on "activity" i.e. requests in the `spring-cloud-azure-appconfiguration-config-web` library as its focus is on Spring Web, and if there are no incoming requests we don't want to make unneeded check to the App Configuration service.

If you want to use some other way of triggering refresh checks you can just use the `spring-cloud-azure-appconfiguration-config` library and do something like this:

```java
@Autowired 
AppConfigurationRefresh appConfigurationRefresh;

...

public void myMethod(...) {
   ...
   appConfigurationRefresh.refreshConfigurations();
   ...
}
```

the `refreshConfigurations` method is async, but will return a `Future<Boolean>` if a refresh event was triggered. Which if true will cause a refresh, but there is no way to know how long the refresh will take.

**Comment by oceansv** [comment]
@mrm9084  I am planning to do something like this 

import com.microsoft.azure.spring.cloud.config.AppConfigurationRefresh;

@component
public class configPoller {

@Autowired
AppConfigurationRefresh appConfigurationRefresh;

@Scheduled(fixedDelay = 30000)
public void scheduleFixedDelayTask() {
	System.out.println(" ----   refreshing");
	appConfigurationRefresh.refreshConfigurations();
}
}

That means i am trying to refresh after every 30 sec. (If it actually getting refreshed or not i am not interested i just want to get the changes after almost a predicted and constant time, and dont want to rely on activity).
Do u see any issue in above approach.


 Can i use event grid  web hook approach or event hub approach? Are they ready to be used in production?

**Comment by mrm9084** [comment]
@oceansv That should work fine for a way to check for a refresh.

We are working on a web hook approach at the moment, a single instance version is in the current SNAPSHOT build. We are still working on one that will update multiple instances. I would wait for the full release before using it in prod.

Because of how Azure Web Hooks work they need validation done on the client side, https://docs.microsoft.com/azure/event-grid/webhook-event-delivery, which is why we are making the change. If you don't want to wait you could use event hub to trigger an azure function that calls the Spring Actuator refresh endpoint.

If you are looking for multi instance refresh you will also need to set us Spring Cloud Bus to propagate the message across multiple instances, the Spring Cloud Bus docs show how to do this.

We hope to have the multi instance refresh in the next major release of the package. Though it will still continue to rely on activity to cause the actual refresh, we will just be causing the cache to be expired with the web hook.

**Comment by oceansv** [comment]
@mrm9084 will it be possible to provide a feature in the new realease like,  when a refresh endpoint is called or communicated through service bus.

1) cache is expired  (which you are doing)
2) Client User is given a choice to register a spring  component  method, which if registered by user will get invoked and have the full update event info as well , in this case user can take his own action if he wants to reload config at that time itself as well as take the action to recreate some spring bean (or some other custom work) based on what key has changed.

Just saying

**Comment by oceansv** [comment]
@mrm9084  Just want to clarify whether its necessary to create a config java class separately with some prefix to get values from appconfig , because i am planning to retrieve it directly from spring environment, I will inject environment in beans wherever i need properties , because environment properties are getting refreshed as well when something is changing and i dont need to classify based on prefix. Just wanted to confirm will the approach is good to go with , as i didnt see it in any document?

**Comment by zhenlan** [comment]
@mrm9084 you have any suggestions for @oceansv's question?

**Comment by ericalone** [comment]
I have a similar issue: 

@ConfigurationProperties(prefix = "config")
public class MessageProperties {
    private String message;
   ...
} 
public class HelloController {
    private final MessageProperties properties;

    public HelloController(MessageProperties properties) {
        this.properties = properties;
    }

   @Value("${config.message}")
   private String message;

  return "message from @value = " + message + "\n message from MessageProperties = " + properties.message;
}

Issue Elaboration:
1. config.message = "value1" initially
2. config.message is changed to "value2" in app config
3. By default 30 s of cache refresh is expected
4. properties.message = "value2" while message = "value1" -- means properties.message picking up the change in Azure App Configuration but Value annotation didn't pickup the change, anything special?

**Comment by EthanNguyen132** [comment]
Hi all, I'm facing the same problem. This official guide from Azure doesn't work at all.
Changing property value doesn't reflect without an app restart. (Spring Boot 2.2.x/2.3.x & spring-cloud-azure-appconfiguration-config 1.2.7)

https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app

**Comment by zhenlan** [comment]
@mrm9084 any suggestions?

**Comment by PbALpi7xEX** [comment]
I was going to post a new issue/question but this exact question was asked here. It seems setting classes annotated with @ConfigurationProperties is not required... I removed mine and my properties are still being loaded and accessible in my Spring Boot app.

Currently running Spring 2.3.9 and Azure App configuration web client v1.2.9... Am I missing something here?

> 
> 
> @mrm9084 Just want to clarify whether its necessary to create a config java class separately with some prefix to get values from appconfig , because i am planning to retrieve it directly from spring environment, I will inject environment in beans wherever i need properties , because environment properties are getting refreshed as well when something is changing and i dont need to classify based on prefix. Just wanted to confirm will the approach is good to go with , as i didnt see it in any document?

**Comment by PbALpi7xEX** [comment]
> I was going to post a new issue/question but this exact question was asked here. It seems setting classes annotated with ConfigurationProperties is not required... I removed mine and my properties are still being loaded and accessible in my Spring Boot app environment.
> 
> Currently running Spring 2.3.9 and Azure App configuration web client v1.2.9... Am I missing something here?


I'll answer my own question here.. essentially this is a Spring Boot design decision... whether to use the environment or type safe structured properties ([https://docs.spring.io/spring-boot/docs/2.3.9.RELEASE/reference/html/spring-boot-features.html#boot-features-external-config-typesafe-configuration-properties](https://docs.spring.io/spring-boot/docs/2.3.9.RELEASE/reference/html/spring-boot-features.html#boot-features-external-config-typesafe-configuration-properties))

Using a properties object lets you easily inject it into various beans, instead of explicitly referencing each individual property... just a bit more work upfront to setup your objects.. but I guess you decide what you want as objects, and leave the rest as environment references.

**Comment by mrm9084** [comment]
@PbALpi7xEX, configurations load form Azure App Configuration are created as Property Sources. You should be able to use them in any way you would use ones loaded from the local configuration file. I think I was just giving an example.
