### ISSUE TITLE
Not able to call authorization service with `json` body whereas with form-data it works

### ISSUE THREAD

**Issue by ashwintastic** [Azure/AppConfiguration#390]
Hi

Getting response with form-data, headers `{Content-type: application/json}`
![as-form-data-1 PNG](https://user-images.githubusercontent.com/11703081/90103068-87e84800-dd5f-11ea-93fd-0ad2e73a95f4.jpg)

Getting error with `json` body I'm using headers `{Content-type: application/json}` in both cases
![as-json-1 PNG](https://user-images.githubusercontent.com/11703081/90103007-6be4a680-dd5f-11ea-8bd3-a3264bd014d2.jpg)

**Comment by zhenlan** [comment]
@ashwintastic this GitHub repo is specifically for Azure App Configuration service and your question does not appear to be directly related. Closing.

**Comment by abhilasharora** [comment]
@ashwintastic Based on your other issue, I believe you're trying to authenticate with Azure Resource Manager in order to use the `/Microsoft.AppConfiguration/configurationStores/{storeName}/listKeyValue` API.

The process to retrieve client credentials for service-to-service authentication uses `OAuth 2.0` protocol that adheres to [RFC 6749](https://tools.ietf.org/html/rfc6749#section-4.1.3). Based on this specification, the access token request should have a content type of `application/x-www-form-urlencoded`. You can find sample examples in [documentation](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow) of client credential grant flow in Azure Active Directory.
