### ISSUE TITLE
Configuration not refreshing with Azure Function using DI.

### ISSUE THREAD

**Issue by hem-sharma** [Azure/AppConfiguration#396]
Using Azure function's DI with app configuration is having issues with refreshing IConfiguration.
```c#
           IConfiguration config = new ConfigurationBuilder()
                .AddAzureAppConfiguration(options =>
                {
                    options.Connect(Environment.GetEnvironmentVariable(PrimaryConfigStoreKey))
                            .Select(KeyFilter.Any, "Core")
                            .ConfigureRefresh(refreshOptions =>
                            {
                                refreshOptions.SetCacheExpiration(TimeSpan.FromMinutes(minutesToRefresh));
                            })
                            .UseFeatureFlags(featureflagoptions =>
                            {
                                featureflagoptions.CacheExpirationTime = TimeSpan.FromMinutes(minutesToRefresh);
                                featureflagoptions.Label = "Core";
                            });
                    configurationRefresher = options.GetRefresher();
                }, true).Build();

            serviceDescriptors.AddSingleton(config);
            serviceDescriptors.AddFeatureManagement(config);
            serviceDescriptors.AddSingleton(configurationRefresher);
```

and within the function, I'm resolving IConfiguration as:

```c#

        private readonly IConfiguration _configuration;
        private readonly IConfigurationRefresher _configurationRefresher;
        private readonly IFeatureManagerSnapshot _featureManagerSnapshot;

        public TestFunction(IConfiguration configuration, IFeatureManagerSnapshot featureManagerSnapshot, IConfigurationRefresher configurationRefresher)
        {
            _configuration = configuration;
            _configurationRefresher = configurationRefresher;
            _featureManagerSnapshot = featureManagerSnapshot;
        }

        [FunctionName("TestFunction")]
        public async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req)
        {
            await _configurationRefresher.RefreshAsync();
            var a = await _featureManagerSnapshot.IsEnabledAsync("Test");
            return new OkObjectResult(Startup.Configuration.GetSection("ConfigKeyName"));
        }

```

As I can see feature-flags are refreshing within a specified interval but there is no change in IConfiguration section. Can someone from the team provide any information on this?

**Comment by abhilasharora** [comment]
@hem-sharma In order to refresh configuration other than feature flags, the key-label pairs to be refreshed need to be explicitly registered for refresh using the [Register ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationrefreshoptions.register?view=azure-dotnet-preview#Microsoft_Extensions_Configuration_AzureAppConfiguration_AzureAppConfigurationRefreshOptions_Register_System_String_System_String_System_Boolean_) method.

In case you'd like all settings for the `Select` clause in your code to be refreshed, the recommended way is to add a sentinel key to your configuration, and then register refresh for it using the `Register` method. This will ensure that whenever that key changes, the updated values are retrieved for all settings. More details can be found [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationrefreshoptions.register?view=azure-dotnet-preview#Microsoft_Extensions_Configuration_AzureAppConfiguration_AzureAppConfigurationRefreshOptions_Register_System_String_System_String_System_Boolean_).

**Comment by hem-sharma** [comment]
Thanks @abhilasharora, Is it possible to provide '*' wildcards in the Register method?

**Comment by abhilasharora** [comment]
At this time, wildcards like `*` are not supported in the `Register` method and are treated as literals.

**Comment by hem-sharma** [comment]
And what is the definition of change for that particular key, **value**, or just an **edit/save**?

**Comment by abhilasharora** [comment]
Changes are detected based on the `ETag` for that key-label pair in the underlying storage. A simple edit/save in the UI could change the `ETag`. Requests sent through the API without a conditional header like `IfMatch` or `IfNoneMatch` will also change the `ETag`, while requests sent with a conditional header may or may not change it.
