### ISSUE TITLE
AddFeatureManagement in xUnit fixture?

### ISSUE THREAD

**Issue by kirk-marple** [Azure/AppConfiguration#403]
I've figured out how to use AddAzureAppConfiguration in my xUnit fixture, when setting up configuration, but I can't figure out how to call AddFeatureManagement since I don't have a service collection.

I want to use IFeatureManager via DI, in my unit tests, but it doesn't seem like there's any way to build an instance without using services.AddFeatureManagement?

Am I missing something, or anyone have a suggestion on how to do this within a unit test?

**Comment by zhenlan** [comment]
@kirk-marple you may like to check out the step 3 of this document
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-dotnet#connect-to-an-app-configuration-store

I know the title of the document is about .NET Framework, but since all relevant libraries are .NET Standard libraries, the code works in .NET Core as well. It shows an example of how to create your own `IServiceCollection` instance and you can use it in your xunit.

**Comment by kirk-marple** [comment]
Ah perfect, thanks @zhenlan .  I'll try that out. I skipped over that page since it said .NET Framework.

**Comment by jimmyca15** [comment]
@kirk-marple 

It looks like this was resolved. Please feel free to re-open if not.

**Comment by mihaipanait** [comment]
> how did you used AddAzureAppConfiguration in your xUnit fixture? Can you give an example please?
