### ISSUE TITLE
ConfigureKeyVault does not support all functionality of UseAzureKeyVault 

### ISSUE THREAD

**Issue by klogan12** [Azure/AppConfiguration#420]
I have been using below to read passwords from vault via app configuration.

 o.Connect(Environment.GetEnvironmentVariable("ConnectionString"))
                .Select(KeyFilter.Any, LabelFilter.Null)
                .UseAzureKeyVault(kvClient)
                .ConfigureRefresh(ro =>
                    ro.Register("Sentinel", LabelFilter.Null, refreshAll: true)
                      .SetCacheExpiration(TimeSpan.FromSeconds(60)));

KvCLient  comes from 
AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
            KeyVaultClient kvClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
            

UseAzureKeyVault is deprecated in lastest release of  dot net library with Configure Key Vault. But it requires client ID.
Is there a way to use MSI and RBAC.

.ConfigureKeyVault(kv =>
                {
                    kv.SetCredential(new DefaultAzureCredential());
                })

I want to authenticate with logged in user credentials without using giving clientId . It worked with the previous approach.

**Comment by abhilasharora** [comment]
@klogan12 You could use the following credentials to use managed identity for authentication. Unlike `KeyVaultClient` with `AzureServiceTokenProvider`, these credentials would only work when deployed to an Azure resource that supports managed identity, but not in your local development environment.

```` csharp
kv.SetCredential(new ManagedIdentityCredential());
````

In order to have the same code work for both Azure and local development environment, the following credentials can be used. This will work in your local development environment only if one of the [supported credentials](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) is set up and available in your environment.

```` csharp
kv.SetCredential(new DefaultAzureCredential());
````

**Comment by jimmyca15** [comment]
It looks like this has been answered. Please re-open if any further explanation is needed.
