### ISSUE TITLE
Azure.RequestFailedException: 'Service request failed. Status: 431 (Request Header Fields Too Large)

### ISSUE THREAD

**Issue by shubham8886** [Azure/AppConfiguration#423]
My application is hosted on Azure WebApp. I am using AAD authentication and we are experiencing Error code# 431.

**Comment by jimmyca15** [comment]
@shubham8886 this may be due to the size of the AAD token being used to authenticate the request. **Without providing the token itself** are you able to provide the **size** of an AAD Token that causes this issue?

The AAD Token is included in the "Authorization" HTTP header in the HTTP request sent to Azure App Configuration. The format looks like below if you would like to take it out of one of your requests

`Authorization: Bearer {aadToken}`

The value of the **token is sensitive**, so it shouldn't be pasted here, but the size can help us diagnose the issue.

Let me know if you need more details on how to get the value of the aad token.

**Comment by shubham8886** [comment]
> @shubham8886 this may be due to the size of the AAD token being used to authenticate the request. **Without providing the token itself** are you able to provide the **size** of an AAD Token that causes this issue?
> 
> The AAD Token is included in the "Authorization" HTTP header in the HTTP request sent to Azure App Configuration. The format looks like below if you would like to take it out of one of your requests
> 
> `Authorization: Bearer {aadToken}`
> 
> The value of the **token is sensitive**, so it shouldn't be pasted here, but the size can help us diagnose the issue.
> 
> Let me know if you need more details on how to get the value of the aad token.

**Comment by shubham8886** [comment]
@jummyca15 I am not able to get the size of the request. can you help me in that, if you are aware of it

**Comment by jimmyca15** [comment]
Are you able to reproduce this issue locally? If so there are multiple options. My first choice would be to use [fiddler](https://www.telerik.com/download/fiddler) to capture the HTTP request that has a 431 response. Then you could inspect it and read the headers that are being sent.
