### ISSUE TITLE
Access to Read-Only Access Keys at ARM creation

### ISSUE THREAD

**Issue by duanekord** [Azure/AppConfiguration#427]
I have an Azure Function that uses the connection string to retrieve values from AppConfig and KV at startup. Easy, works perfectly.

I have ARM templates that create everything during my YAML Pipeline deployment. It creates my Managed Identity, My Key Vault, and my AppConfig store.

**What I am trying to accomplish is** - during my ARM creation -> add the read-only connection string from my newly created  AppConfigStore and pass it to store in my newly created KeyVault.  So I can then access that connection string in my Function Startup.

Any thoughts on how to automate this.

**Comment by zhenlan** [comment]
@duanekord you brought up a very good question. We do realize there are challenges to pick a specific connection string (eg. the primary read-only) from the ARM template. We are in discussion internally about what options we can offer. We will keep this thread posted.

**Comment by Postlagerkarte** [comment]
@zhenlan : Any update on this? We are using Terraform and need to get access to the read-only connection string from the created resource.

**Comment by jimmyca15** [comment]
@Postlagerkarte the only way to obtain keys (connection strings as well) in an ARM template is via the [ListKeys](https://docs.microsoft.com/en-us/rest/api/appconfiguration/configurationstores/listkeys) operation. It falls a bit short in ARM templates because there is no way to ensure that a specific read-only connection string is pulled from the ListKeys response. We are in the process of enhancing the API to be able to filter on the server side. Once this is available it will be possible to deterministically get a read-only key in ARM template.

**Comment by jimmyca15** [comment]
We have discussed this, and in an effort to address the concerns here we'd like to offer an alternative approach that we feel solves the root problem of read-only access in a more optimal manner.

Granting read-only access to an Azure App Configuration instance is best done with [AAD authentication](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#overview). This means having an identity that can be granted the [App Configuration Data Reader](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration) role, and using that identity to access Azure App Configuration. Using AAD authentication should alleviate the need to acquire specific keys during deployment. If possible, we'd suggest seeing if this an option to setup read-only access.
