### ISSUE TITLE
PrivateLinkActive: The operation cannot be performed because private link is active on the resource.

### ISSUE THREAD

**Issue by wictorwilen** [Azure/AppConfiguration#432]
When trying to add a key/value to my App Configuration using an ARM template I get the following error:

```
Deployment failed. Correlation ID: fe88c311-a77e-44ab-9a1f-327cee3e644b. {
  "code": "PrivateLinkActive",
  "message": "The operation cannot be performed because private link is active on the resource."
}
```

I do have a private link on my App Config service, but how do I work around this using ARM?

**Comment by MSGaryWang** [comment]
You might reference https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest#az_appconfig_update and enable public network access with your store.

**Comment by wictorwilen** [comment]
@MSGaryWang - thanks. So your recommendation would be during ARM script executing this is enabled, changes to the key/values are done, then public network access is disabled?

**Comment by MSGaryWang** [comment]
It depends on if any other service from internet needs to access the store with private endpoint enabled.

**Comment by wictorwilen** [comment]
@MSGaryWang - this is just when running my ARM templates. As an example - it works great with ARM templates for setting KeyVault secrets and PrivateLink, but for App Config with Private Link I get this error. Seems like they should behave the same.

**Comment by zhenlan** [comment]
@wictorwilen good question. Maybe add some context here will help our understanding.

By default, when the private link is enabled, your App Config store will deny all requests that are *not* sent from your VNET (via the private endpoints). This gives you peace of mind because you know even if someone got the credentials of your store somehow, they still cannot access your data unless they also get into your VNET.

The ARM template, however, is not running from your VNET. As of today, there is also no way to enforce that the ARM template can only be submitted from a VNET. This is the reason the ARM template for data access will stop working once you turn on the private link. If we allow data access from the ARM template, it will basically allow anyone to access your data from outside of your VNET (anyone can submit an ARM template from the internet). We don't want to do it without your explicit permission. This is why you will need to enable public network access to your store for the ARM template to work.

**Comment by zhenlan** [comment]
@wictorwilen please let me know if you have further questions. Closing for now.
