### ISSUE TITLE
az appconfig kv import - importing the key vault content type in incorrect format with extra slashes

### ISSUE THREAD

**Issue by manvkaur** [Azure/AppConfiguration#438]
Command Used:
`az appconfig kv import -n $appConfigStore -s file --path $filePath --format json --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" --yes --separator ":"`

Azure CLI version:
2.15.1

Input json:
```
{
  "aaabbb.temp": {
    "secret": "{\"uri\":\"https://key-vault-name.vault.azure.net/secrets/secret1\"}"
  },
  "aaabbb.temp2": {
    "secret": "{\"uri\":\"https://key-vault-name.vault.azure.net/secrets/secret1\"}"
  }
}
```

Exported result from portal:
```
{
    "aaabbb.temp2": {
        "secret": "\"{\\\"uri\\\":\\\"https://key-vault-name.vault.azure.net/secrets/secret1\\\"}\""
    },
    "aaabbb.temp": {
        "secret": "\"{\\\"uri\\\":\\\"https://key-vault-name.vault.azure.net/secrets/secret1\\\"}\""
    }
}
```
Extra slashes resulting in failure of retrieval of secrets.

**Comment by avanigupta** [comment]
Hi @manvkaur, if you are interested in importing/exporting Key Vault references from AppConfig to JSON file, please use Azure CLI for both import and export. We currently don't have this functionality in Azure portal but we are working on it. 
The behavior you are seeing is because you are importing through CLI and exporting through portal. To import/export through Azure CLI, you can use the following commands:

**Export KeyVault references to JSON file:**

`az appconfig kv export -n $appConfigStore -d file --path $filePath --format json --yes`

Your exported json file will look like this:
```
{
  "aaabbb.temp2:secret": {
    "uri": "https://key-vault-name.vault.azure.net/secrets/secret1"
  },
  "aaabbb.temp:secret": {
    "uri": "https://key-vault-name.vault.azure.net/secrets/secret1"
  }
}
```

**Import KeyVault references from JSON file:**

`az appconfig kv import -n $appConfigStore -s file --path $filePath --format json --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" --yes`

Hope that helps!

**Comment by manvkaur** [comment]
Hi @avan

> Hi @manvkaur, if you are interested in importing/exporting Key Vault references from AppConfig to JSON file, please use Azure CLI for both import and export. We currently don't have this functionality in Azure portal but we are working on it.
> The behavior you are seeing is because you are importing through CLI and exporting through portal. To import/export through Azure CLI, you can use the following commands:
> 
> **Export KeyVault references to JSON file:**
> 
> `az appconfig kv export -n $appConfigStore -d file --path $filePath --format json --yes`
> 
> Your exported json file will look like this:
> 
> ```
> {
>   "aaabbb.temp2:secret": {
>     "uri": "https://key-vault-name.vault.azure.net/secrets/secret1"
>   },
>   "aaabbb.temp:secret": {
>     "uri": "https://key-vault-name.vault.azure.net/secrets/secret1"
>   }
> }
> ```
> 
> **Import KeyVault references from JSON file:**
> 
> `az appconfig kv import -n $appConfigStore -s file --path $filePath --format json --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" --yes`
> 
> Hope that helps!

Hi @avanigupta ,

This is happening from since Dec 2, 2020. Our applications are failing to retrieve the secrets due to incorrect references.
I have to manually add each and every key in the key vault because references are not being saved properly.

Portal export used to work perfectly fine before that.

If you need repro or more details, please hit me on my MS alias.

**Comment by avanigupta** [comment]
@manvkaur, a couple of questions:
- Did you recently upgrade your CLI? If yes, what version were you using before Dec 2nd?
- How did you create the appsettings.json file that is being imported? It looks like you used Export from Azure Portal to get this file.

**Comment by manvkaur** [comment]
> @manvkaur, a couple of questions:
> 
> * Did you recently upgrade your CLI? If yes, what version were you using before Dec 2nd?
> * How did you create the appsettings.json file that is being imported? It looks like you used Export from Azure Portal to get this file.


Hi @avanigupta 

1. The build agent gets frequently updated with the latest cli version. We are 2.16.0 today
2. Yes sample one was exported from azure portal in July, later we kept on adding more settings.
Suggestion was taken from below comment on another issue of app configuration 
https://github.com/Azure/AppConfiguration/issues/268#issuecomment-661864075

**Comment by avanigupta** [comment]
In early August 2020, we released JSON content-type support in Azure CLI starting with version 2.10.0. That's why I'm curious to know how your application did not break sooner if that's the only thing that changed. I'm guessing you were still using version 2.9.0 or earlier until Dec 2nd and then directly upgraded to 2.16.0?

This is what changed with the 2.10.0 release in August: [Leverage content-type to store JSON key-values in App Configuration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type#import-json-key-values-from-a-file)

Since the content-type of Key Vault references is also a valid JSON content-type, your Key Vault references don't need to be stored as string values in your appsettings.json file. Currently, you are storing the Key Vault reference as a string value: 
`"{\"uri\":\"https://key-vault-name.vault.azure.net/secrets/secret1\"}"`

But actually the Key vault reference is supposed to be a JSON object:
`{"uri": "https://key-vault-name.vault.azure.net/secrets/secret1"}`

Please note that you cannot export using Azure Portal and import using Azure CLI and get the same result. As I mentioned earlier, we are working on adding the same support in Azure Portal, but until that is released, **_please use only Azure CLI to import/export Key Vault references properly_**. 

To fix this problem for your application, you need to export all your Key Vault references again using Azure CLI. You can use this command to export:
`az appconfig kv export -n $appConfigStore -d file --path $filePath --format json --yes`

This is what your appsettings.json file should contain this:
```json
{
  "aaabbb.temp2:secret": {
    "uri": "https://key-vault-name.vault.azure.net/secrets/secret1"
  },
  "aaabbb.temp:secret": {
    "uri": "https://key-vault-name.vault.azure.net/secrets/secret1"
  }
}
```

Once you have fixed your appsettings.json file, you can import the file as usual using this command:
`az appconfig kv import -n $appConfigStore -s file --path $filePath --format json --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" --yes`

**Comment by manvkaur** [comment]
Thank you @avanigupta 
This has resolved my issue. I have changed the input json to the suggested format.
Also, we were using az cli version earlier than 2.9.0 and upgrade to 2.15.0 caused the issue.
Thanks for the update.

**Comment by zeqk** [comment]
Thank you very much! This solution helped me too!

This another documentacion [Azure App Configuration support for configuration files: File content profile: default](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-default) is wrong or outdated

![image](https://user-images.githubusercontent.com/11799393/181332098-157da9e2-ced3-4353-b6dd-c3854fd1bf51.png)

**Comment by zhenlan** [comment]
Glad this 2-year-old thread still helps :)

There are multiple ways to achieve the same result. 
- If you prefer to have a multi-level JSON file (i.e., a `ConnectionString` node is under a `Database` node), you can use the CLI command outlined in the document with the `--separator` parameter. This may work better for JSON files with complex hierarchical structures. The document is not wrong or outdated. 
- But if you prefer to have a one-level JSON file (i.e., `Database:ConnectionString` is one node and the separator is part of your key name), the CLI command discussed in this thread works. I can see why this may be preferred because you don't have to JSON-escape the Key Vault reference uri anymore.

**Comment by zeqk** [comment]
Thank you @zhenlan! This is true for import no-key-vault-references

But in the case of import key-vault-references, if you use the format suggested in the [documentation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-default) the result is a invalid key vault reference

![image](https://user-images.githubusercontent.com/11799393/181809692-ba6bb21f-6161-4767-b42f-84c2148d7b6d.png)

The result in Azure Portal

![image](https://user-images.githubusercontent.com/11799393/181810124-c08cce09-a071-401c-ab3f-605a5d4c5588.png)

**Comment by tdyds** [comment]
> Thank you @zhenlan! This is true for import no-key-vault-references
> 
> But in the case of import key-vault-references, if you use the format suggested in the [documentation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-default) the result is a invalid key vault reference

Was led to this thread for exactly this reason. It's a little bit of a nuisance if you're working with local configuration files that you use to import into azure app configuration regularly, that you can't use the same "regular" JSON format for both regular configurations and key vault references.

**Comment by zhenlan** [comment]
The doc is updated to use the preferred approach for Key Vault reference import discussed in this thread
https://github.com/MicrosoftDocs/azure-docs-pr/pull/216354

**Comment by ogubernatorov-gl** [comment]
After some investigation problem was detected in `separator` argument.
Input json:
`json
{
  "Password1": {
    "uri": "https://kv-sample-d3n5a.vault.azure.net/secrets/db-password"
  },
  "NestedPassword" : {
    "Password1": {
      "uri": "https://kv-sample-d3n5a.vault.azure.net/secrets/db-password"
    }
  }
}
`

Import with separator:
`
az appconfig kv import --label test --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" --name appcfg-sample-d3n5a --source file --path test.sec.json --format json -y --separator .
`

![Image](https://github.com/user-attachments/assets/a79dfa18-c6da-44b4-a76f-f83602d1450d)

Import without separator:
`
az appconfig kv import --label test --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" --name appcfg-sample-d3n5a --source file --path test.sec.json --format json -y
`


![Image](https://github.com/user-attachments/assets/998ad097-ed1a-44c2-9b92-2a47d3d5c9ab)

And again none of 2 acceptable... 
Only way is to provide dotted path in json keys (not handy and bad looking way...):
`json
{
  "Password1": {
    "uri": "https://kv-sample-d3n5a.vault.azure.net/secrets/db-password"
  },
  "NestedPassword.Password1": {
      "uri": "https://kv-sample-d3n5a.vault.azure.net/secrets/db-password"
    }
}
`

**Comment by albertofori** [comment]
Hi @ogubernatorov-gl,

Just a bit of clarification here, especially with regards to your json input:

1. Without a separator: We do not flatten json objects and the value of the top-level keys are considered your intended value. So in your case, your top-level keys would have to map to your keyvault references.

2. With a separator: We flatten json objects down to the point where the value is a primitive (string, number, or null).
You can also specify a `depth` property when you specify a `separator`. This will prevent flattening beyond your preferred point. But note that the values that correspond to the keys at the depth you stop flattening have to be your intended values across the board.  

Since your intended values are at different depth, the current way to import once is as you have mentioned. Rename your keys to make sure your values exist at the same depth.

**Comment by zhenlan** [comment]
The doc update PR has been merged. You can check out the latest document. If you have key names at different depths for key vault references, you may consider KVSet content profile https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-kvset.

**Comment by ogubernatorov-gl** [comment]
Thanks for the response and clarifications. Will try to pickup one of the approaches.
