### ISSUE TITLE
Refresher does not refresh changed keys when a pattern is used

### ISSUE THREAD

**Issue by jbrezina** [Azure/AppConfiguration#455]
I have a stored key-value in Azure AppConfiguration like this:
`key:subkey = value`
But when the value is changed, the refresher does not reload it when I use the '*' patter like in the code bellow.
```private static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureAppConfiguration((hostingContext, config) => {  
			...
			config.AddAzureAppConfiguration(options => options
				...
				.Select("key*", label)
				.ConfigureRefresh(options => options
					.Register("key*", label)
					.SetCacheExpiration(TimeSpan.FromSeconds(30))
				)
			);
		})
```
I have to use the subkey to register for changes, which is not managable with a lot of subkeys.
`.Register("key:subkey", label)`

**Comment by zhenlan** [comment]
@jbrezina the `AzureAppConfigurationRefreshOptions.Register` API expects a *key name* instead of a *key filter* for its parameter, so your code is actually registered to refresh for the key with name `key*` instead of keys that start with `key`. Please consider using a sentinel key for config update as recommended in this tutorial.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core

**Comment by jbrezina** [comment]
Why is it possible to Select keys with a pattern, but not to refresh them with a pattern?

**Comment by zhenlan** [comment]
@jbrezina please see #153 for more details and share any further feedback there.
