### ISSUE TITLE
GetFeatureNames returns Configuration Keys instead of feature names

### ISSUE THREAD

**Issue by MichaCo** [Azure/AppConfiguration#540]
Hi,

I'm currently playing with the app-configuration service and I think I found a pretty strange bug.

When I use both, configuration K/Vs and feature flagging, and filter the feature flags in a way that it doesn't return anything. `GetFeatureNamesAsync` all the sudden returns configuration keys.

I'm using the following configuration/setup:

```csharp
.AddAzureAppConfiguration(o =>
{
    o.Connect("");

    // Example key is MV:Dashboard:Logging:Default
    // Gets keys with prefix
    o.Select("MV:Dashboard:*", "LabelA");
    o.TrimKeyPrefix("MV:Dashboard:");

    o.UseFeatureFlags(f =>
    {
        // Works if there are keys with that prefix
        // f.Select("App.Dashboard.*", "LabelA");

        f.Select("doesntexist.*", "LabelA");
    });
});
```

Values in Azure App Configuration:

![image](https://user-images.githubusercontent.com/5837539/128637114-0a473492-9437-498a-99b7-caf32006cdd6.png)

`manager.GetFeatureNamesAsync()` now returns `Logging` as a feature name.

If I use a feature filter via `Select` which returns the one configured feature flag, `Logging` is not getting returned and only the one actual feature `App.Dashboard.All.UseAwesomeFeature` gets returned.

I don't think that's the expected behavior, at least I didn't find any documentation which would say so.

Thanks
Michael

**Comment by jimmyca15** [comment]
This is due to the ability to define features at the root level of `IConfiguration`. The Microsoft.FeatureManagement library switches to this mode if [no "FeatureManagement" section is found](https://github.com/microsoft/FeatureManagement-Dotnet/blob/c24f4fd8b72a006543641522a528eaa81bee4525/src/Microsoft.FeatureManagement/ConfigurationFeatureDefinitionProvider.cs#L182) in the application's configuration. In your case, that condition is hit if you don't pull down any features.

I can see how this can be a bit confusing. Any modification to this behavior would be a breaking change, but as we prepare for an upcoming 3.x release train we may be able to look back at this and make it require an opt-in.

For now, a workaround is to add

```
"FeatureManagement": {}
```

into your `appsettings.json` file. This will prevent the feature management library from thinking that you want to fall back to the root for features. It will not interfere with any features retrieved from Azure App Configuration.

**Comment by MichaCo** [comment]
Ok, thanks for the explanation.
