### ISSUE TITLE
What would be the possible reason for null returned value for the configuration item?

### ISSUE THREAD

**Issue by dawwa** [Azure/AppConfiguration#55]
**Question**:
I was following the tutorial, but get NULL returned value, wondering how to troubleshoot it and what would be the possible reason for it? 
Please see the screenshot that shows the null property value in the injected object at HomeController ctor, if I put the following line to resolve the registered config, it is also has null value for the LUIS_ENV property.

            // TBD: Cannot Resolve this
            var dynamicSettings = services.BuildServiceProvider().GetService<IOptionsSnapshot<DynamicSettings>>();

Please see the attached screenshot of my code. Thanks.

![ConfigureServices](https://user-images.githubusercontent.com/44714043/56868840-cdd39e00-69ac-11e9-90d4-c2c5eaa22bb9.JPG)
![NullProperty](https://user-images.githubusercontent.com/44714043/56859905-e0ff5300-6945-11e9-8656-0591ca4ffe3b.JPG)

**Comment by jimmyca15** [comment]
There are a few moving pieces here that all would need to be inspected to ensure that we know what the issue is, but from a glance it looks like you should be calling `services.Configure<DynamicSettings>(this.Configuration.GetSection("DynamicSettings")` rather than `services.Configure<DynamicSettings>(this.Configuration.GetSection("DynamicSettings:LUIS_ENV")`

Can you provide the code where you are setting up the AzureAppConfiguration provider? (minus any connection strings of course)

**Comment by dawwa** [comment]
Thanks @jimmyca15
