### ISSUE TITLE
Is it possible to put Azure App Configuration behind Azure Front Door?

### ISSUE THREAD

**Issue by david-peden-q2** [Azure/AppConfiguration#567]
I have set up three resource groups, each with their own instance of App Configuration. All keys/values are synchronized between the configuration stores. I have also created an Azure Front Door instance and associated frontend, backendpool, and route linking the frontend and backendpool via forwarding. Everything is wired up successfully. However, when I attempt to call into the front door config endpoint, I get an authentication failure in my app config client.

```
Azure.Identity.AuthenticationFailedException
DefaultAzureCredential authentication failed.
...
Azure.Identity.AuthenticationFailedException
ClientSecretCredential authentication failed.
...
Azure.RequestFailedException
Service request failed.
Status: 400 (Bad Request)

Content:
{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://config.[redacted].com was not found in the tenant named [redacted]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 5db9f6b7-0f95-4740-b352-180c20e67300\r\nCorrelation ID: 7506487d-dad1-410f-b6ff-566e95434f28\r\nTimestamp: 2021-10-21 18:06:46Z","error_codes":[500011],"timestamp":"2021-10-21 18:06:46Z","trace_id":"5db9f6b7-0f95-4740-b352-180c20e67300","correlation_id":"7506487d-dad1-410f-b6ff-566e95434f28","error_uri":"https://login.microsoftonline.com/error?code=500011"}
```

Calling the uri of any/all of the individual config services (backends) works fine.

**Comment by jimmyca15** [comment]
A clean solution for this scenario is going to require changes on our side and after having looked at this we have already started working on them. Until this work is finished on our side, any solution is going to be a workaround at best and I wouldn't consider it production ready. I'll provide some details on your questions though.

> Edit: having said all that, since I have Front Door strictly set up for request forwarding, I'm not sure why the request doesn't make it to a config service endpoint for token acquisition unless the client terminates early by inspecting the uri of the request (to verify that the endpoint ends in *.azconfig.io) before actually sending it.

The reason that the request does not make it to your front door instance is because before any request is sent to App Configuration (or in your case, to Azure Front Door) a request is first made to AAD. This request to AAD tries to get an AAD token to authenticate with Azure App Configuration. The token request uses the URI of the App Configuration instance as a parameter. However, in your case you are passing the URI of Azure Front Door to the App Configuration client, and the token request is using your Azure Front Door URI. AAD is considering this an invalid parameter and is throwing the error that you mentioned. This is happening all before the client makes a request to App Configuration.

> Is there a way to create a custom HTTP pipeline that will enable this to work? I’ve pulled down the code from https://github.com/Azure/azure-sdk-for-net and have been reviewing the Azure.Data.AppConfiguration, Azure.Identity, and Azure.Core solutions but I haven’t successfully pieced anything together yet.

It's more of a problem with the parameters being passed to `TokenCredential`. If you extend [`DefaultAzureCredential`](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) override [`DefaultAzureCredential.GetTokenAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential.gettokenasync?view=azure-dotnet#Azure_Identity_DefaultAzureCredential_GetTokenAsync_Azure_Core_TokenRequestContext_System_Threading_CancellationToken_) you will see the incorrect AAD scope parameter I mentioned above in [`TokenRequestContext.Scopes`](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokenrequestcontext.scopes?view=azure-dotnet#Azure_Core_TokenRequestContext_Scopes). A correct scope for App Configuration would use one of our [documented AAD audiences](https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-azure-ad#audience). 

E.g.
Invalid App Configuration scope: "https://myfrontdoor.azure.com/.default"
Valid App Configuration scope: "https://*.azconfig.io"

However, pitfalls can occur even if overriding the invalid scope to the valid scope that I mentioned. And this is something that needs to be addressed on our side.

**Comment by davidpeden3** [comment]
@jimmyca15 thanks for the detailed response. I no longer have access to the email that I originally posted under so didn't see your response until now. thank you for your help.

**Comment by zhenlan** [comment]
@jimmyca15 has this issue been addressed?

**Comment by jimmyca15** [comment]
@davidpeden3

Were you able to come to a working solution, or are you still seeking guidance on this issue?

**Comment by mwmardis** [comment]
@jimmyca15 Are there still plans on your side to address this use case of allowing Azure App Configuration to be put behind Azure Front Door?

**Comment by davidpeden3** [comment]
> Were you able to come to a working solution, or are you still seeking guidance on this issue?

hey @jimmyca15 i'm no longer working on the effort that originally triggered this question. having said that, i still think it would be a valuable addition. i am likely to start a new endeavor soon where i would be interested in this capability. as @mwmardis asked, i would also like to know the official stance on this topic. thanks!

**Comment by jimmyca15** [comment]
@mwmardis @davidpeden3 

There was a blocker that prevented this scenario when the original issue was filed. Now it should be good to go. The change that we made is that we started supporting the following AAD token audience: `https://azconfig.io`.

Now the following suggestion I gave in an earlier comment no longer has any blockers and should be able to be used to make this scenario work.

> If you extend [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) override DefaultAzureCredential.GetTokenAsync you will see the incorrect AAD scope parameter I mentioned above in [TokenRequestContext.Scopes](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokenrequestcontext.scopes?view=azure-dotnet#Azure_Core_TokenRequestContext_Scopes). A correct scope for App Configuration would use one of our [documented AAD audiences](https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-azure-ad#audience).

In the case of the original comment, the scope would have been "https://config.[redacted].com/.default", as extracted from the client's endpoint, whereas it should be the App Configuration scope like "https://azconfig.io"

Let me know if that needs any more clarification.

Also, do you mind sharing some of the motivation behind a setup like this? Is it for perceived availability increase for example?

**Comment by davidpeden3** [comment]
The idea is to emulate (replicate?) the redundancy [automatically provided by Azure Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/general/disaster-recovery-guidance). When using ACS backed by AKV, it makes no sense not to have redundant ACS instances. Instead of relying on a chain of configured instances, relying on a pool fronted by Azure Front Door means that all clients get nearest/best ACS rather than all going to the configured instances in a fall-through scenario. Why ACS doesn't offer the same guarantee of redundancy as AKV feels like an oversight.
