### ISSUE TITLE
How can we  implement push model(through azure app configuration) in azure functions  

### ISSUE THREAD

**Issue by SAMBHAV1997** [Azure/AppConfiguration#583]
I have implemented dynamic configuration(through azure app configuration) in an Azure Functions app using this link(https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-azure-functions-csharp), 
This is poll model, Next I want to implement dynamic configuration using push model in azure functions.

**Comment by zhenlan** [comment]
Great, you already have the poll model implemented because in general, the push model is implemented with two modifications on top of the poll model.
1. A much longer config-refresh cache expiration time, for example, an hour or a day. As config refresh will normally be triggered by push events, this serves as a safety net just in case the push events were missed.
2. A callback function that will respond to the push notification event and you call `SetDirty` to signal the immediate need of config refresh.

App Configuration sends push notification events via Event Grid. Azure Functions is one of the handler services Event Grid supports.
- If your Function app has only one instance, you can add step 2 above responding to the Event Grid notification directly.
- If your Function app has more than one instance, you can add Service Bus to broadcast the Event Grid notification to all instances of your Function app as suggested in this [document](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh). Please make sure to create separate Service Bus subscription for each instance. An example can be found in #549.
