### ISSUE TITLE
Overriding Entire Array Doesn't Affect Already Bound Option Objects

### ISSUE THREAD

**Issue by keggster101020** [Azure/AppConfiguration#597]
When attempting to override an entire array originally set in appsetting.json with a new array value in azure app config results in an inconsistent state for already configured objects vs IConfiguration object.

Example array in appsettings:
```json
{
  "Test":
    {
       "Array": ["prop1","prop2","prop3"]
    }
}
```

Registration of Azure app configuration was done following the doc guide [here](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core5x).
App configuration is the last registered provider so it should override appsettings.json.

Binding of the test object is done in startup as follows:
```csharp
services.Configure<TestSettings>(Configuration.GetSection("Test"));
```

with `TestSettings` looking like:
```csharp
public class TestSettings
	{
		public IList<string> Array{ get; set; } = new List<string>();
	}
```

I set a key-value ref in app config portal as follows:
`key = Test:Array` | `value= [override]` 
>I also tried setting it to ["override"] & I tried setting the content type to "application/json" the result is the same

If I create a test class and inject `IConfiguration` as well as `IOptionsSnapshot<TestSettings>` they contain different values for `["Test:Array"]`

```csharp
public class TestClass
{
  public TestClass(IConfiguration config, IOptionsSnapshot<TestSettings> snapshot)
  {
        var configRef = config.GetSection("Test")["Array"]"; //returns "[override]"
        var snapshotRef = snapshot.Value.Array; // returns ["prop1","prop2","prop3"]
  }
}
```

Is there something I'm missing? It was my understanding that you could override entire JSON objects according to [this doc](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type)

----------
Microsoft.Azure.AppConfiguration.AspNetCore nuget version:  4.4.0
ASP.NET Core version: 5.0

**Comment by avanigupta** [comment]
Hi @keggster101020, 

If your appsettings.json file contains the following key-values:
```
{
  "Test":
    {
       "Array": ["prop1","prop2","prop3"]
    }
}
```

This will be flattened to three key-values in your application configuration:
`Test:Array:0 = "prop1"`
`Test:Array:1 = "prop2"`
`Test:Array:2 = "prop3"`

In order to override all 3 configurations, you need to provide 3 corresponding values in AppConfig with a JSON content type.  For example, you can add the following key-value in your config store:

Key | Value | Content-Type
--- | --- | ---
Test:Array | ["override1", "override2", "override3"] | application/json

This will override all three key-values in your application configuration to:
`Test:Array:0 = "override1"`
`Test:Array:1 = "override2"`
`Test:Array:2 = "override3"`


If you add an array with just one value (like in your example), this will only override the value corresponding to key `Test:Array:0` in your application configuration. The other two keys, `Test:Array:1` and `Test:Array:2` will still have the value from appsettings.json file because nothing is provided in AppConfig to override them.

**Comment by keggster101020** [comment]
@avanigupta that makes sense as to why the IOptions typed version of the config didn't change values, but what about the drift between IOptions and IConfiguration? It seems like setting of values should be an all or nothing operation if that is under the control of configuration provider.

**Comment by avanigupta** [comment]
@keggster101020 , if you set the value in AppConfig in the correct JSON syntax, i.e. value = ["override"] and content-type=application/json, you will see that both `IConfiguration` and `IOptionsSnapshot<TestSettings>` will reflect the overridden value from AppConfig:

```
public class TestClass
{
  public TestClass(IConfiguration config, IOptionsSnapshot<TestSettings> snapshot)
  {
            var configRef = config["Test:Array:0"]; // returns "override"
            var snapshotRef = snapshot.Value.Array; // returns ["override","prop2","prop3"]
  }
}
```

**Comment by keggster101020** [comment]
@avanigupta thanks for clearing that up, perhaps something could be added to [this doc](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type) to denote the JSON array functionality for native .NET configuration provider is different than that of consuming it via the SDK/REST if it isn't already captured.

Closing.
