### ISSUE TITLE
How much is Microsoft.FeatureManagement.AspNetCore tied to Azure?

### ISSUE THREAD

**Issue by giggio** [Azure/AppConfiguration#66]
The `Microsoft.FeatureManagement.AspNetCore` package points to this repo as the source. It is not clear if this package is supposed to be used only with Azure AppConfiguration, or as a generic package for feature management. Would you please clarify?

**Comment by jimmyca15** [comment]
@giggio

`Microsoft.FeatureManagement.AspNetCore` is decoupled from Azure App Configuration. It is built on top of .NET Core's `IConfiguration` system and can be used to it's full capabilities simply through the use of an appsettings.json file. It can be thought of as a thin layer on top of existing .NET Core framework packages.

Azure App Configuration exposes a .NET Core configuration provider in the `Microsoft.Extensions.Configuration.AzureAppConfiguration` package which exposes application configuration through the `IConfiguration` interface. This means that Azure App Configuration is a fully supported way of providing feature management data to applications, and also enabling the capability to dynamically enable and disable them during run time.

The reason that the package points here is because we have developed the package, but in the future we can hopefully find a better spot for it :).

We currently have documentation for the package available here: https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core

**Comment by hasansachdev** [comment]
same question. I wanted to use FeatureManagement in my dot net core application that's not hosted on Azure. 
Is that possible without using Azure SDK and AzureAppConfiguration?

**Comment by ArieJones** [comment]
You can. Currently using it on AWS with a custom database configuration provider... so no dependency on Azure..

**Comment by ArieJones** [comment]
Though I would rather be on Azure for this project. :)
