### ISSUE TITLE
[Spring boot] Feature flags is not updated.

### ISSUE THREAD

**Issue by alexander-icj** [Azure/AppConfiguration#683]
Given: spring boot application

pom.xml
```
azure-spring-cloud-appconfiguration-config-web 2.6.0
azure-spring-cloud-feature-management-web 2.6.0
```
bootstrap.properties
```
spring.cloud.azure.appconfiguration.stores[0].connection-string=${APP_CONFIGURATION_CONNECTION_STRING}
spring.cloud.azure.appconfiguration.stores[0].feature-flags.enabled=true
spring.cloud.azure.appconfiguration.stores[0].monitoring.enabled=true
```

TaskController.java
```
@Component
@Path("user-task")
public class TaskController {
    
    @Autowired
    FeatureManager featureManager;

    @GET
    @Path("details")
    public String details() {
               
        for (String featureName : featureManager.getAllFeatureNames()) {
            Boolean isEnabled = featureManager.isEnabledAsync(featureName).block();      
            System.out.println(featureName + ": " + isEnabled);
        }
        return "test";
    }    
}
```
After the change features on feature manager (add new or turn on/off), the data does not change. Shows the state that was loaded when the application was started. 

What I tried:

- wait 5, 10, 30 minutes (after change on manager)
- add `spring.cloud.azure.appconfiguration.stores[0].monitoring.triggers[0].key=feature-cache-key`  and change it on `Configuration explorer`
- сhanged the version to `appconfiguration-config-web `to `2.9.0` and `feature-management-web` to `2.8.0`
- set `spring.cloud.azure.appconfiguration.refresh-interval= 1m`
- set `spring.cloud.azure.appconfiguration.stores[0].monitoring.feature-flag-refresh-interval= 1m`

All these attempts did not get сhanged feature flags after update on azure portal.

**Comment by mrm9084** [comment]
@alexander-icj, If I am looking at this correctly it is because you aren't using Spring Web for your Controllers, which the library is based on.

You can drop down to `azure-spring-cloud-appconfiguration-config` which doesn't depend on Spring Web, but doesn't have auto refresh baked in.  You can use the Manual refresh option of the library https://microsoft.github.io/spring-cloud-azure/docs/azure-app-configuration/2.6.0/reference/html/index.html#manual. It is a rather simple method call to have us check for a refresh, assuming the refresh-interval has passed.

**Comment by alexander-icj** [comment]
@mrm9084, thanks for the recommendation, but it didn't help.

pom.xml
```
azure-spring-cloud-appconfiguration-config 2.9.0
azure-spring-cloud-feature-management 2.8.0
```

bootstrap.properties
```
spring.cloud.azure.appconfiguration.stores[0].connection-string=${APP_CONFIGURATION_CONNECTION_STRING}
spring.cloud.azure.appconfiguration.stores[0].feature-flags.enabled=true
```
TaskController.java

```
@Component
@Path("user-task")
public class TaskController {
    
    @Autowired
    FeatureManager featureManager;

    @Autowired(required = false)
    private AppConfigurationRefresh refresh;

    @GET
    @Path("details")
    public String details() throws Exception {
        refresh.refreshConfigurations();    
        
        for (String featureName : featureManager.getAllFeatureNames()) {
            Boolean isEnabled = featureManager.isEnabledAsync(featureName).block();      
            System.out.println(featureName + ": " + isEnabled);
        }
        return "test";
    }    
}

```
refreshConfigurations didn't help. 
I change the feature flags on the azure portal (turn on/off). But the data is not updated. 
The data cached after the first launch.

**Comment by mrm9084** [comment]
@alexander-icj, If you look at the logs is a refresh triggered? You should see a log similar to the one here https://microsoft.github.io/spring-cloud-azure/docs/azure-app-configuration/2.6.0/reference/html/index.html#configuration-refresh. Where is should log that a refresh is happening.

There are two options:

1. If a refresh is triggered, then your component isn't in the `@refreshScope`, and you will need to update it to be.
2. If a refresh isn't triggered then something is missing.

One thing I have noticed is that your bootstrap.properties is missing something like

```properties
spring.cloud.azure.appconfiguration.stores[0].monitoring.triggers[0].key=sentinel
```

Without it, you should be having an error thrown on startup. I am assuming something is there but want to double check, otherwise we are looking at the wrong things.

**Comment by alexander-icj** [comment]
Thanks, that helped. Final code:

pom.xml
```
azure-spring-cloud-appconfiguration-config 2.9.0
azure-spring-cloud-feature-management 2.8.0
```

bootstrap.properties
```
spring.cloud.azure.appconfiguration.stores[0].connection-string=${APP_CONFIGURATION_CONNECTION_STRING}
spring.cloud.azure.appconfiguration.stores[0].feature-flags.enabled=true
spring.cloud.azure.appconfiguration.stores[0].monitoring.triggers[0].key=sentinel
```

TaskController.java

```
@Component
@Path("user-task")
public class TaskController {
    
    @Autowired
    FeatureManager featureManager;

    @Autowired(required = false)
    private AppConfigurationRefresh refresh;

    @GET
    @Path("details")
    public String details() throws Exception {
        refresh.refreshConfigurations();    
        
        for (String featureName : featureManager.getAllFeatureNames()) {
            Boolean isEnabled = featureManager.isEnabledAsync(featureName).block();      
            System.out.println(featureName + ": " + isEnabled);
        }
        return "test";
    }    
}
```
