### ISSUE TITLE
Adding key-values to Azure App Configuration using Bicep when Private Link enabled

### ISSUE THREAD

**Issue by Daniel-Krzyczkowski** [Azure/AppConfiguration#698]
Hi,

I encountered specific problem.
I deploy Azure App Configuration with Bicep. App Configuration has public access disabled because I want to use Private Link.
When I am trying to add key-values to App Configuration using Bicep, I receive information that access to the App Configuration is forbidden. 
When I change public access to "Enabled", deployment works.
Do you know what it does not work when public access is disabled and Private Link is enabled? For instance for Azure Key Vault I am able to add secrets even when public access is disabled and Private Link is enabled.

I would be grateful for any hints because I am not sure if this is the issue with the service or it should just work like this.

**Comment by zhenlan** [comment]
Hi @Daniel-Krzyczkowski, this is a known limitation for either Bicep or ARM template deployment. Please see the note in the [document](https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager) that I quoted here:

_App Configuration allows key-value data access over a [private link](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-private-endpoint) from your virtual network. By default, when the feature is enabled, all requests for your App Configuration data over the public network are denied. Because the ARM template runs outside your virtual network, data access from an ARM template isn't allowed. To allow data access from an ARM template when a private link is used, you can enable public network access by using the following Azure CLI command. It's important to consider the security implications of enabling public network access in this scenario._

**Comment by Daniel-Krzyczkowski** [comment]
Thank you @zhenlan for a quick response! This was also my suspicion but I wanted to be sure.
Azure Key Vault can be accessed by ARM when public access is enabled but I suppose this is because it provides "NetworkRuleSet" and we can set its property called "bypass" to "AzureServices".

**Comment by drago-draganov** [comment]
@Daniel-Krzyczkowski
Bypass for ARM/Biceps pretty much means public network access. As @zhenlan mentioned above, ARM templates allow to read and write AppConfiguration key-values. That basically translates to proxy calls from a public network. That is the reason for  AppConfiguration to be explicit on calling it out, since it goes outside of the promise of Private Link isolation.

**Comment by Daniel-Krzyczkowski** [comment]
Thank you so much for the answers, all clear now!

**Comment by jimmyca15** [comment]
Looks like this has been answered. Feel free to reach out again if there are any other questions.

**Comment by brazarb** [comment]
So what's the recommended way of handling this when using Private Link isolation?

Currently we use a dedicated host that has access to the resources, and az cli to import the json file kvset into app configuration.

However this is painful to maintain, we have 5 different environments, so 5 different .json files to maintain and is error prone, a couple of weeks ago this caused massive pain, we were adding a app configuration key vault reference which didn't exist, the error message when running the arm-deploy action didn't explicitly mention that and we spent hours trying to figure out what was wrong.

**Comment by Daniel-Krzyczkowski** [comment]
@drago-draganov Thank you so much for the answer. Great to know that this problem is taken under consideration to be solved in the future.
