### ISSUE TITLE
Do all requests to Azure App Configuration count subtract from the quota or only request that result in in a configuration refresh?

### ISSUE THREAD

**Issue by ryanewtaylor** [Azure/AppConfiguration#716]
The [pricing page](https://azure.microsoft.com/en-us/pricing/details/app-configuration/) states that there is a 30,000 requests per hour per resource limit. In addition, more than 200,000 requests per day will result in an overage charge. This seems straight forward enough.

However, the [App Configuration FAQ on estimating the number of requests](https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#how-do-i-estimate-the-number-of-requests-my-application-may-send-to-app-configuration) implies that only requests that result in a refresh count towards the quota. I highlighted the relevant sections below.

![image](https://user-images.githubusercontent.com/1215819/217048567-ebcf0f74-fa0c-43ee-a88a-e93345aea5e5.png)

My question is, what truly counts towards the hourly and data quotas? All requests, only requests resulting in refreshed data, or some other definition?

**Comment by drago-draganov** [comment]
There are a couple things in here:

1. Billing: All successful requests count towards the daily usage. 200,000 requests per day are included with the daily charge. Anything above that is overage.
2. Quota limits: That applies only to throttling. 30,000 requests per hour (read+write) is the minimum guaranteed at the moment. Note that frequent read requests (sentinel key check, burst loading/refresh, etc.) are often intentionally excluded from that limit. That in practice allows for way more than 30,000 requests per hour. The reason for that is to prevent unexpected quota depletion and subsequent persisted HTTP 429 (Too Many Requests) for application deployment, startup, restarts, refresh or monitor for changes, caused by multiple instances in a short period of time.

**Comment by ryanewtaylor** [comment]
@drago-draganov thanks for the explanation! It is much appreciated. 

One question regarding the following...

> Note that frequent read requests (sentinel key check, burst loading/refresh, etc.) are often intentionally excluded from that limit

I plan to be well below the 30,000 / hour quota limit but would like to be prepared to answer questions from our clients about any perceived limitations. Are there more definitive rules for when a request is or is not included in the quota limit? "Often intentionally excluded" implies that sometimes those requests are included in the limit.

**Comment by drago-draganov** [comment]
@ryanewtaylor 

Under the hood: If the request analysis concludes high optimization value (ex. hit a few times per minute, payload size, etc.) it's forced optimized. Optimized requests will not count towards the hourly limit (so the quota is not depleted). That means most of the burst loads/refresh/restarts, sentinel key poll, etc. fit the criteria and end up optimized (preserving the quota for non-optimized requests). If requests aren't optimized, then the hourly limit should be sufficient enough to provide uninterrupted service.

I understand that it's not a hard rule, but hopefully provides some insights. Our goal is to keep the quality of service well beyond any advertised hourly limits and most importantly to prevent blackouts at any cost.

If you can test your projected workload volume, that would be fantastic.

**Comment by ryanewtaylor** [comment]
@drago-draganov once again, thank you! You have been very helpful!
