### ISSUE TITLE
LabelFilter matching pattern

### ISSUE THREAD

**Issue by codehunter13** [Azure/AppConfiguration#742]
Here: https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value is said you can use matching pattern with asterisk in labels:
![image](https://user-images.githubusercontent.com/7559059/232012895-33585767-45ec-4d50-8470-616cff62a598.png)

But when using AzureAppConfiguration.Select the * is not supported. I got the error The characters '*' and ',' are not supported in label filters.

Would be handy to select labels with "1.0.*

**Comment by avanigupta** [comment]
Hi @codehunter13, this is by design. We don't support label filters with `Select` clause because the resulting `IConfiguration` key-values can be unpredictable in case of same key with multiple labels. Please see this issue for more details: https://github.com/Azure/AppConfiguration/issues/647

Let me know if you have a special use case which requires selecting multiple labels with one `Select` clause.

**Comment by draxtor** [comment]
Hi, I think Azure team is overprotective. If I screw the filters or double the keys my bad I'll fix it. This way you took away a  control from me to protect me.
 here is my scenario.
Create One AppConfiguration that would be used by multiple functions for different purposes.
One function is calling an external service the other doesn't so I want to filter configuration of each function by feature.
So func1 will have configs from labels ExtService and AppInsights and func2 only from AppInsights label

**Comment by avanigupta** [comment]
Hi @draxtor, if you know which labels your app wants to load, you could use multiple `Select` statements to load key-values for those labels. But if you have too many labels, you might benefit from implementing key prefixes instead of labels for filtering. Please see this article for learning more about prefix-based filtering: https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-best-practices#key-groupings 

You could then use this API to trim the prefixes before loading key-values into IConfiguration: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.trimkeyprefix?view=azure-dotnet
