### ISSUE TITLE
Add more feature flags by label after app is running

### ISSUE THREAD

**Issue by steven-rothwell** [Azure/AppConfiguration#770]
Our feature flags are not in the configuration explorer, so to listen to multiple labels, I chain the options.UseFeatureFlags method.
```
builder.Configuration.AddAzureAppConfiguration(options => 
{
  options.Connect(connectionString);
  options.UseFeatureFlags(featureOptions =>
  {
    featureOptions.Label = "someLabel";
  }).UseFeatureFlags(featureOptions =>
  {
    featureOptions.Label = "anotherLabel";
  });
});
```
That is done in the Program.cs.  Sometimes a new label will be added while this application is already running and this application will need to listen to all feature flags that have the new label.  I figured we could utilize a configuration key and have it hold an array of strings (aka labels) and periodically check this configuration key for changes.  If there is a new label, then have the application start listening to all feature flags with that label.

One, is there a way to basically append `UseFeatureFlags` with a new label after the application is running?
Two, if so, is there a built in way to check for changes in the configuration key and if so, append the `UseFeatureFlags`?  I know right now, there's `ConfigureRefresh` that you can register a sentinel that refreshes the cache of feature flags. Is there something similar that I can attach some code to when the interval expires?

**Comment by jimmyca15** [comment]
This looks to be continuing [this discussion](https://github.com/microsoft/FeatureManagement-Dotnet/issues/234) in this issue in the Microsoft/FeatureManagement-Dotnet repo.

In that discussion, the issue was brought up about the possible indeterministic behavior of selecting multiple labels without specifying ordering. I do hear you that it is blocking your scenario, but I would like to understand the scenario a bit better to make sure to come to the right solution.

My first question is, how is label being used here? I'm wondering if label is being used in such a way that including it as a [key namespace](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-best-practices#key-groupings) would be a better option. In that case, a solution would already be present.

What I mean is that if you have data like the following

| key                          | (flag name) | value | label    |
|------------------------------|-------------|-------|----------|
| .appconfig.featureflag/beta  | beta        | true  | testapp  |
| .appconfig.featureflag/alpha | alpha       | false | otherapp |


It may be a solution to instead have

| key                                   | (flag name)    | value | label        |
|---------------------------------------|----------------|-------|--------------|
| .appconfig.featureflag/testapp/beta   | testapp/beta   | true  | ( no label ) |
| .appconfig.featureflag/otherapp/alpha | otherapp/alpha | false | ( no label ) |

and watch all feature flags with no label.

**Comment by jimmyca15** [comment]
> Also, I don't know if you saw in the other discussion, but our feature flags are not merged into our configurations. So, I don't think utilizing the key namespace solution is an option.

I'm not quite sure what you mean here. The namespace solution seems more appealing to me the more I look at this situation. I don't get the blocker about merging flags with configuration.

**Comment by zhenlan** [comment]
@steven-rothwell please let us know when you have more to share. Closing for now.
