### ISSUE TITLE
Dry Run Option with Azure CLI

### ISSUE THREAD

**Issue by thepaulmacca** [Azure/AppConfiguration#792]
I'd like to use the `az appconfig kv import` commands instead of the `AzureAppConfigurationPush@5` task, but I don't see a dry run option documented.

The task has a `DryRun` option though - can someone point me to the code for the `AzureAppConfigurationPush@5` task please, so I can try to suss it out?

Thanks

**Comment by albertofori** [comment]
Hi @thepaulmacca,

Just to clarify, do you want to see the changes that would be made to your store when a set of key-values are being imported? If so, when the `--yes` or `-y` flag is not specified in the import command, we show a preview of the key-values that are going to be added, updated and deleted (in the event where a user specifies the `--strict` flag).

Kindly let me know if this serves the intended purpose. Thanks!

**Comment by thepaulmacca** [comment]
Thanks for coming back to me @albertofori 

We're currently using terraform to create keys, but looking to move over to importing them via configuration files instead

The dry run would be used in a CI pipeline ideally, so users could see what will be changed before merge, so would need to bypass the prompt if possible

Hope that makes sense

**Comment by brental** [comment]
@thepaulmacca You can workaround the prompt by executing the import command in an AzureCli task with powershell and wrapping the call in a try catch block. The command will throw an exception when it tries to prompt because there is no user input available but you can catch and handle it. 

You will also want to set the powerShellIgnoreLASTEXITCODE input parameter of the task to true otherwise the task still gets a failed result.

These two together do mean the task will probably never fail for any reason though so consider that when using this approach. Given the downsides of this approach using the AzureAppConfigurationPush@5 task might be better, but it does have its own downsides as well.

**Comment by thepaulmacca** [comment]
Thanks for the comment, I'll give it a try but I think the simplest option here is to stick with the task in all honesty

**Comment by brental** [comment]
Yeah, I tried the approach I outlined and got it work, but ended up going back to the task.
