### ISSUE TITLE
Integration with azure functions.

### ISSUE THREAD

**Issue by klogan12** [Azure/AppConfiguration#82]
NuGet install fails with version conflict for newtonsoft.json.  How to get this working with function apps?

Install-Package : NU1107: Version conflict detected for Newtonsoft.Json. Install/reference Newtonsoft.Json 11.0.2 directly to project TurinFunctionApps to resolve this issue. 
 DemoFunctionApps -> Microsoft.Extensions.Configuration.AzureAppConfiguration 1.0.0-preview-008520001 -> Newtonsoft.Json (>= 11.0.2) 
 DemoFunctionApps -> Microsoft.NET.Sdk.Functions 1.0.28 -> Newtonsoft.Json (= 9.0.1).
At line:1 char:1

**Comment by zhenlan** [comment]
Hi @klogan12, did you try to add the package reference of the version 11.0.2 `Newtonsoft.Json` package to your `DemoFunctionApps` directly?

**Comment by klogan12** [comment]
That conflicts with version requirement of microsoft.net.sdk.functions.  sdk.function requires Newtonsoft json version 9 and below.

**Comment by zhenlan** [comment]
The issue is caused by the `Microsoft.NET.Sdk.Functions` package asking for the specific 9.0.1 version of `Newtonsoft.json`. The solution is to force it to use a different version by adding 11.0.2 version of `Newtonsoft.json` **directly** to your project. I remember I tried it last time and it worked for me. @klogan12, did you get a chance to try it out or do you still get the error?

**Comment by klogan12** [comment]
It worked. Thanks
