### ISSUE TITLE
Get certificate from Key Vault in kubernetes.io/tls secret type

### ISSUE THREAD

**Issue by antoineozenne-at-leocare** [Azure/AppConfiguration#821]
Is it possible to get a certificate from Key Vault in a `kubernetes.io/tls` secret type? For now, I have a PFX certificate in a Key Vault. When I reference it in the `AzureAppConfigurationProvider` resource, I get it in a `Opaque` secret type, in a binary format (base64 encoded). I would like to get my certificate in a `kubernetes.io/tls` secret type (in a PEM format) to be able to use it with [ingress-nginx](https://github.com/kubernetes/ingress-nginx) for example.

This way, I could replace all my `SecretProviderClass` resources by only one `AzureAppConfigurationProvider` to get all my configuration (configuration and secrets), for each of my applications. I find that `AzureAppConfigurationProvider` is more comfortable and easy to use than `SecretProviderClass`.

**Comment by RichardChen820** [comment]
It's a good feature enhancement we can consider to support. Currently, we only support generating keyVaultReferece type items into one single `Secret` with opaque type because we can't predict how many secrets would be selected by the user, and theoretically, users could do whatever they want to use the secrets in opaque type `Secret`.

The user case you mentioned is indeed a reasonable scenario to us, and also drives us to consider supporting even more `Secret` types other than it.

After doing some necessary investigation, I just give my proposal the way of supporting different types of `Secret` here.

1. Add a new `resolveCertBasedSecret` flag under `keyVaults` section.
    Since Azure KeyVault's secret client API has the capability to identify whether a keyVault secret belongs to a certificate in its back, specify this  `resolveCertBasedSecret` flag to true can dictate the provider to generate a kuberentes.io/tls type `Secret` naming with the keyVaultReference item key in AppConfig, all other non-cert based secrets are stored into an opaque `Secret` like currently we have.

2. We preserve a special name for the Tag  `.azconfig.k8s.secret.type`, users could override the default `Secret` generation behavior by specifying it in AppConfig keyVaultReference item.
![image](https://github.com/Azure/AppConfiguration/assets/99175581/a97df31d-c57d-4875-bf34-1e6cc8f3458b)
We can support 'opaque', 'kubernetes.io/tls', 'kubernetes.io/ssh-auth' etc.. type in this tag. Once a keyVaultRefrence item is tagged with a type, the provider would generate it into a single `Secret` naming with the item key in AppConfig in certain type

**Comment by antoineozenne-at-leocare** [comment]
Thank you @RichardChen820. If I understand your proposal, it can handle several secrets and of different types in only one `AzureAppConfigurationProvider` resource, so it is great.

**Comment by RichardChen820** [comment]
@antoineozenne-at-leocare  It supports generating TLS type Secrets in the latest v1.3.0, please check this [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default#types-of-secret) for the detail.

**Comment by RichardChen820** [comment]
Close this issue, feel free to reactivate if you have more questions.
