### ISSUE TITLE
Unable to import all keys in a json file

### ISSUE THREAD

**Issue by chassq** [Azure/AppConfiguration#934]
We think an issue to the one below is happening in the azure portal. 

https://github.com/Azure/AppConfiguration/issues/386

We are trying to import in bulk from one configuration service to another. We export from one app configuration instance as json and imports into another app configuration instance. Only a subset of our keys are being imported. We are using the ':' separator in our keys. Can you confirm how this should be done?

**Comment by zhenlan** [comment]
Hi @chassq, in your scenario, you can import from one App Configuration store to another store directly without using a file.

If for some reasons you have to use a file, I'd recommend you export and import using a [file with the KVSet content type](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-kvset) because it will preserve all properties of key-values as how they are from the source App Configuration store. I understand this feature may not be available in Azure portal yet. You can use the Azure CLI for now. The feature is coming to the portal soon.

**Comment by chassq** [comment]
Hey @zhenlan , For us we needed to use a file as we wanted to change some setting prefixes during transfer. Glad to hear that may be in the portal soon!

**Comment by ivywei0125** [comment]
Hi @chassq, the support about export and import using a [file with the KVSet content type](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-kvset) is already released. 
You could go to your resource's page on the Azure portal, open the **Operations** -> **Import/export** menu, and select **KVSet** in **File content profile** option.
![Snipaste_2024-07-22_16-41-23](https://github.com/user-attachments/assets/49c82dee-c079-43b5-968e-e83c388db905)

**Comment by chassq** [comment]
Thank you! That seems to work well!

**Comment by ivywei0125** [comment]
[like]  Yu Wei reacted to your message:
________________________________
