### ISSUE TITLE
Documentation not updated with latest API version 2024-05-01

### ISSUE THREAD

**Issue by Pavkum007** [Azure/AppConfiguration#992]
The following link still refers to App Config store API version 2023-03-01. But I believe the latest API version is 2024-05-01

https://learn.microsoft.com/en-us/azure/templates/microsoft.appconfiguration/configurationstores?pivots=deployment-language-terraform

Request to update the documentation. Thank you.

**Comment by zhenlan** [comment]
@austintolani can you help check?

**Comment by austintolani** [comment]
Update on this: These docs are automatically generated from our REST API Specifications. I've made contact with the repo owner who is in the process of running an update to regenerate these docs with our current REST API Specifications. 

In the future, they plan to run the update once a week so that content doesn't go stale.

**Comment by austintolani** [comment]
[Doc](https://learn.microsoft.com/en-us/azure/templates/microsoft.appconfiguration/configurationstores?pivots=deployment-language-terraform) is now updated with the newest API version. As mentioned in comment above, in the near future this content should be automatically updated.
